/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[repr(align(8))]
#[derive(Debug)]
pub struct RustPromiseAwaiter {
    pub _bindgen_opaque_blob: [u64; 12usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RustPromiseAwaiter"][::std::mem::size_of::<RustPromiseAwaiter>() - 96usize];
    ["Alignment of RustPromiseAwaiter"][::std::mem::align_of::<RustPromiseAwaiter>() - 8usize];
};
