/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[repr(align(8))]
#[derive(Debug)]
pub struct GuardedRustPromiseAwaiter {
    pub _bindgen_opaque_blob: [u64; 15usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of GuardedRustPromiseAwaiter"]
        [::std::mem::size_of::<GuardedRustPromiseAwaiter>() - 120usize];
    ["Alignment of GuardedRustPromiseAwaiter"]
        [::std::mem::align_of::<GuardedRustPromiseAwaiter>() - 8usize];
};
