paths-ignore:
  - "src/workerd/api/node/crypto_keys-test.js"
  - "src/workerd/api/node/crypto_dh-test.js"
  - "src/workerd/jsg/url-test-corpus-success.h"
  - "src/workerd/api/node/tests/crypto_x509-test.js"
  - "src/workerd/api/node/tests/fixtures/dh_private.pem"
  - "src/workerd/api/node/tests/fixtures/dsa_private_pkcs8.pem"
  - "src/workerd/api/node/tests/fixtures/ed25519_private.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_private_encrypted.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_pss_private_2048_sha1_sha1_20.pem"
  - "src/workerd/api/node/tests/fixtures/dsa_private_1025.pem"
  - "src/workerd/api/node/tests/fixtures/ec_p256_private.pem"
  - "src/workerd/api/node/tests/fixtures/ed448_private.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_private.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_pss_private_2048_sha256_sha256_16.pem"
  - "src/workerd/api/node/tests/fixtures/dsa_private_encrypted_1025.pem"
  - "src/workerd/api/node/tests/fixtures/ec_p384_private.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_private_2048.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_private_pkcs8_bad.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_pss_private_2048_sha512_sha256_20.pem"
  - "src/workerd/api/node/tests/fixtures/dsa_private_encrypted.pem"
  - "src/workerd/api/node/tests/fixtures/ec_p521_private.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_private_4096.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_private_pkcs8.pem"
  - "src/workerd/api/node/tests/fixtures/x25519_private.pem"
  - "src/workerd/api/node/tests/fixtures/dsa_private.pem"
  - "src/workerd/api/node/tests/fixtures/ec_secp256k1_private.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_private_b.pem"
  - "src/workerd/api/node/tests/fixtures/rsa_pss_private_2048.pem"
  - "src/workerd/api/node/tests/fixtures/x448_private.pem"
