load(":vendor_test.bzl", "vendored_py_wd_test")

vendored_py_wd_test("fastapi")

vendored_py_wd_test("beautifulsoup4")

vendored_py_wd_test(
    "python-workers-runtime-sdk",
)

# vendored_py_wd_test("scipy")
