// Copyright (c) 2017-2022 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0

#include <workerd/jsg/jsg.h>

#include <kj/array.h>
#include <kj/compat/brotli.h>
#include "zlib.h"

#include <limits>
#include <stdint.h>

namespace workerd::api::node {

// Implements utilities in support of the Node.js Zlib
class ZlibUtil final : public jsg::Object {
public:
  ZlibUtil() = default;
  ZlibUtil(jsg::Lock&, const jsg::Url&) {}

  // Certain zlib constants are defined by NodeJS itself
  static constexpr auto Z_MIN_CHUNK = 64;
  static constexpr auto Z_MAX_CHUNK = 128 * 1024;
  static constexpr auto Z_DEFAULT_CHUNK = 16 * 1024;
  static constexpr auto Z_MIN_MEMLEVEL = 1;

  static constexpr auto Z_MAX_MEMLEVEL = 9;
  static constexpr auto Z_DEFAULT_MEMLEVEL = 8;
  static constexpr auto Z_MIN_LEVEL = -1;
  static constexpr auto Z_MAX_LEVEL = 9;
  static constexpr auto Z_DEFAULT_LEVEL = Z_DEFAULT_COMPRESSION;
  static constexpr auto Z_MIN_WINDOWBITS = 8;
  static constexpr auto Z_MAX_WINDOWBITS = 15;
  static constexpr auto Z_DEFAULT_WINDOWBITS = 15;

  using ZlibModeValue = uint8_t;
  enum class ZlibMode: ZlibModeValue {
    NONE,
    DEFLATE,
    INFLATE,
    GZIP,
    GUNZIP,
    DEFLATERAW,
    INFLATERAW,
    UNZIP,
    BROTLI_DECODE,
    BROTLI_ENCODE
  };

  uint32_t crc32Sync(kj::Array<kj::byte> data, uint32_t value);

  JSG_RESOURCE_TYPE(ZlibUtil) {
    JSG_METHOD_NAMED(crc32, crc32Sync);

    // zlib.constants (part of the API contract for node:zlib)
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_NO_FLUSH, Z_NO_FLUSH);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_PARTIAL_FLUSH, Z_PARTIAL_FLUSH);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_SYNC_FLUSH, Z_SYNC_FLUSH);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_FULL_FLUSH, Z_FULL_FLUSH);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_FINISH, Z_FINISH);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_BLOCK, Z_BLOCK);

    JSG_STATIC_CONSTANT_NAMED(CONST_Z_OK, Z_OK);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_STREAM_END, Z_STREAM_END);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_NEED_DICT, Z_NEED_DICT);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_ERRNO, Z_ERRNO);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_STREAM_ERROR, Z_STREAM_ERROR);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_DATA_ERROR, Z_DATA_ERROR);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_MEM_ERROR, Z_MEM_ERROR);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_BUF_ERROR, Z_BUF_ERROR);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_VERSION_ERROR, Z_VERSION_ERROR);

    JSG_STATIC_CONSTANT_NAMED(CONST_Z_NO_COMPRESSION, Z_NO_COMPRESSION);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_BEST_SPEED, Z_BEST_SPEED);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_BEST_COMPRESSION, Z_BEST_COMPRESSION);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_DEFAULT_COMPRESSION, Z_DEFAULT_COMPRESSION);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_FILTERED, Z_FILTERED);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_HUFFMAN_ONLY, Z_HUFFMAN_ONLY);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_RLE, Z_RLE);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_FIXED, Z_FIXED);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_DEFAULT_STRATEGY, Z_DEFAULT_STRATEGY);
    JSG_STATIC_CONSTANT_NAMED(CONST_ZLIB_VERNUM, ZLIB_VERNUM);

    JSG_STATIC_CONSTANT_NAMED(CONST_DEFLATE, static_cast<ZlibModeValue>(ZlibMode::DEFLATE));
    JSG_STATIC_CONSTANT_NAMED(CONST_INFLATE, static_cast<ZlibModeValue>(ZlibMode::INFLATE));
    JSG_STATIC_CONSTANT_NAMED(CONST_GZIP, static_cast<ZlibModeValue>(ZlibMode::GZIP));
    JSG_STATIC_CONSTANT_NAMED(CONST_GUNZIP, static_cast<ZlibModeValue>(ZlibMode::GUNZIP));
    JSG_STATIC_CONSTANT_NAMED(CONST_DEFLATERAW, static_cast<ZlibModeValue>(ZlibMode::DEFLATERAW));
    JSG_STATIC_CONSTANT_NAMED(CONST_INFLATERAW, static_cast<ZlibModeValue>(ZlibMode::INFLATERAW));
    JSG_STATIC_CONSTANT_NAMED(CONST_UNZIP, static_cast<ZlibModeValue>(ZlibMode::UNZIP));
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODE, static_cast<ZlibModeValue>(ZlibMode::BROTLI_DECODE));
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_ENCODE, static_cast<ZlibModeValue>(ZlibMode::BROTLI_ENCODE));

    JSG_STATIC_CONSTANT_NAMED(CONST_Z_MIN_WINDOWBITS, Z_MIN_WINDOWBITS);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_MAX_WINDOWBITS, Z_MAX_WINDOWBITS);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_DEFAULT_WINDOWBITS, Z_DEFAULT_WINDOWBITS);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_MIN_CHUNK, Z_MIN_CHUNK);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_MAX_CHUNK, Z_MAX_CHUNK);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_DEFAULT_CHUNK, Z_DEFAULT_CHUNK);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_MIN_MEMLEVEL, Z_MIN_MEMLEVEL);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_MAX_MEMLEVEL, Z_MAX_MEMLEVEL);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_DEFAULT_MEMLEVEL, Z_DEFAULT_MEMLEVEL);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_MIN_LEVEL, Z_MIN_LEVEL);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_MAX_LEVEL, Z_MAX_LEVEL);
    JSG_STATIC_CONSTANT_NAMED(CONST_Z_DEFAULT_LEVEL, Z_DEFAULT_LEVEL);

    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_OPERATION_PROCESS, BROTLI_OPERATION_PROCESS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_OPERATION_FLUSH, BROTLI_OPERATION_FLUSH);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_OPERATION_FINISH, BROTLI_OPERATION_FINISH);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_OPERATION_EMIT_METADATA, BROTLI_OPERATION_EMIT_METADATA);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_PARAM_MODE, BROTLI_PARAM_MODE);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_MODE_GENERIC, BROTLI_MODE_GENERIC);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_MODE_TEXT, BROTLI_MODE_TEXT);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_MODE_FONT, BROTLI_MODE_FONT);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DEFAULT_MODE, BROTLI_DEFAULT_MODE);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_PARAM_QUALITY, BROTLI_PARAM_QUALITY);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_MIN_QUALITY, BROTLI_MIN_QUALITY);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_MAX_QUALITY, BROTLI_MAX_QUALITY);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DEFAULT_QUALITY, BROTLI_DEFAULT_QUALITY);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_PARAM_LGWIN, BROTLI_PARAM_LGWIN);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_MIN_WINDOW_BITS, BROTLI_MIN_WINDOW_BITS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_MAX_WINDOW_BITS, BROTLI_MAX_WINDOW_BITS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_LARGE_MAX_WINDOW_BITS, BROTLI_LARGE_MAX_WINDOW_BITS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DEFAULT_WINDOW, BROTLI_DEFAULT_WINDOW);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_PARAM_LGBLOCK, BROTLI_PARAM_LGBLOCK);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_MIN_INPUT_BLOCK_BITS, BROTLI_MIN_INPUT_BLOCK_BITS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_MAX_INPUT_BLOCK_BITS, BROTLI_MAX_INPUT_BLOCK_BITS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_PARAM_DISABLE_LITERAL_CONTEXT_MODELING,
                              BROTLI_PARAM_DISABLE_LITERAL_CONTEXT_MODELING);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_PARAM_SIZE_HINT, BROTLI_PARAM_SIZE_HINT);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_PARAM_LARGE_WINDOW, BROTLI_PARAM_LARGE_WINDOW);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_PARAM_NPOSTFIX, BROTLI_PARAM_NPOSTFIX);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_PARAM_NDIRECT, BROTLI_PARAM_NDIRECT);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_RESULT_ERROR, BROTLI_DECODER_RESULT_ERROR);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_RESULT_SUCCESS, BROTLI_DECODER_RESULT_SUCCESS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT,
                              BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT,
                              BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_PARAM_DISABLE_RING_BUFFER_REALLOCATION,
                              BROTLI_DECODER_PARAM_DISABLE_RING_BUFFER_REALLOCATION);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_PARAM_LARGE_WINDOW,
                              BROTLI_DECODER_PARAM_LARGE_WINDOW);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_NO_ERROR, BROTLI_DECODER_NO_ERROR);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_SUCCESS, BROTLI_DECODER_SUCCESS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_NEEDS_MORE_INPUT,
                              BROTLI_DECODER_NEEDS_MORE_INPUT);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_NEEDS_MORE_OUTPUT,
                              BROTLI_DECODER_NEEDS_MORE_OUTPUT);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_NIBBLE,
                              BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_NIBBLE);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_RESERVED,
                              BROTLI_DECODER_ERROR_FORMAT_RESERVED);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_META_NIBBLE,
                              BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_META_NIBBLE);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_ALPHABET,
                              BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_ALPHABET);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_SAME,
                              BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_SAME);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_CL_SPACE,
                              BROTLI_DECODER_ERROR_FORMAT_CL_SPACE);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_HUFFMAN_SPACE,
                              BROTLI_DECODER_ERROR_FORMAT_HUFFMAN_SPACE);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_CONTEXT_MAP_REPEAT,
                              BROTLI_DECODER_ERROR_FORMAT_CONTEXT_MAP_REPEAT);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_1,
                              BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_1);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_2,
                              BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_2);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_TRANSFORM,
                              BROTLI_DECODER_ERROR_FORMAT_TRANSFORM);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_DICTIONARY,
                              BROTLI_DECODER_ERROR_FORMAT_DICTIONARY);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_WINDOW_BITS,
                              BROTLI_DECODER_ERROR_FORMAT_WINDOW_BITS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_PADDING_1,
                              BROTLI_DECODER_ERROR_FORMAT_PADDING_1);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_PADDING_2,
                              BROTLI_DECODER_ERROR_FORMAT_PADDING_2);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_FORMAT_DISTANCE,
                              BROTLI_DECODER_ERROR_FORMAT_DISTANCE);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET,
                              BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_INVALID_ARGUMENTS,
                              BROTLI_DECODER_ERROR_INVALID_ARGUMENTS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MODES,
                              BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MODES);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_ALLOC_TREE_GROUPS,
                              BROTLI_DECODER_ERROR_ALLOC_TREE_GROUPS);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MAP,
                              BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MAP);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_1,
                              BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_1);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_2,
                              BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_2);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_ALLOC_BLOCK_TYPE_TREES,
                              BROTLI_DECODER_ERROR_ALLOC_BLOCK_TYPE_TREES);
    JSG_STATIC_CONSTANT_NAMED(CONST_BROTLI_DECODER_ERROR_UNREACHABLE,
                              BROTLI_DECODER_ERROR_UNREACHABLE);
  };
};

#define EW_NODE_ZLIB_ISOLATE_TYPES api::node::ZlibUtil

} // namespace workerd::api::node
