name: 'Setup runner environment'
description: 'Sets up runner environment with proper toolchain for building workerd'
runs:
  using: 'composite'
  steps:
    - name: Setup Linux
      shell: bash
      if: runner.os == 'Linux'
      run: |
        export DEBIAN_FRONTEND=noninteractive
        wget https://apt.llvm.org/llvm.sh
        sed -i '/apt-get install/d' llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 21
        # keep in sync with build/ci.bazelrc
        sudo apt-get install -y -qq --no-install-recommends \
          clang-21 \
          lld-21 \
          libunwind-21 \
          libc++abi1-21 \
          libc++1-21 \
          libc++-21-dev \
          libclang-rt-21-dev \
          llvm-21
        sudo ln -s /usr/bin/llvm-symbolizer-21 /usr/bin/llvm-symbolizer
        sudo ln -s /usr/bin/llvm-profdata-21 /usr/bin/llvm-profdata
        sudo ln -s /usr/bin/llvm-cov-21 /usr/bin/llvm-cov
        echo "build:linux --action_env=CC=/usr/lib/llvm-21/bin/clang" >> .bazelrc
        echo "build:linux --host_action_env=CC=/usr/lib/llvm-21/bin/clang" >> .bazelrc
        echo "build:linux --linkopt=--ld-path=/usr/lib/llvm-21/bin/ld.lld" >> .bazelrc
        echo "build:linux --host_linkopt=--ld-path=/usr/lib/llvm-21/bin/ld.lld" >> .bazelrc
        echo "build:linux --action_env=AR=/usr/lib/llvm-21/bin/llvm-ar" >> .bazelrc
        echo "build:linux --host_action_env=AR=/usr/lib/llvm-21/bin/llvm-ar" >> .bazelrc
    - name: Setup Windows
      shell: pwsh
      if: runner.os == 'Windows'
      # Set a custom output root directory to avoid long file name issues.
      # TODO(cleanup): According to https://github.com/actions/runner-images/blob/win25/20251216.149/images/windows/scripts/build/Configure-DeveloperMode.ps1#L13,
      # this should already be set on the build image, but prior testing indicated CI speedups with
      # it, check if it is actually having any effect.
      run: |
        # Enable Developer Mode to allow Bazel to create real symlinks
        reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" /t REG_DWORD /f /v "AllowDevelopmentWithoutDevLicense" /d "1"
        git config --global core.symlinks true
        git config --show-scope --show-origin core.symlinks
        git config --system core.longpaths true
        [System.IO.File]::WriteAllLines((Join-Path -Path $env:USERPROFILE -ChildPath '.bazelrc'), 'startup --output_user_root=\\\\?\\C:\\tmp')
        # TODO: Test that the build is still compatible with the latest LLVM release
        # choco upgrade llvm --version=21.1.8
    - name: Setup macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # Build using Xcode 16.3 (equivalent to Clang 19)
        sudo xcode-select -s "/Applications/Xcode_16.3.app"
    - name: Configure git hooks
      shell: bash
      # Configure git to quell an irrelevant warning for runners (they never commit / push).
      run: git config core.hooksPath githooks
