load("@rules_rust//rust:defs.bzl", "rust_binary")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

rust_binary(
    name = "race",
    srcs = ["race.rs"],
    edition = "2024",
    target_compatible_with = select({
        "//build/platforms:sanitizer_thread": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)

sh_test(
    name = "tsan-integration-test",
    srcs = ["verify.sh"],
    data = [
        ":race",
        "//build/rust:tsan_rust_std",
    ],
    target_compatible_with = select({
        "//build/platforms:sanitizer_thread": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
