// Copyright (c) 2026 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0

#pragma once

#include <workerd/jsg/modules.capnp.h>
#include <workerd/jsg/wrappable.h>

#include <kj-rs/kj-rs.h>
#include <rust/cxx.h>
#include <v8.h>

#include <kj/function.h>
#include <kj/memory.h>
#include <kj/refcount.h>

// Forward declarations needed by v8.rs.h
namespace workerd::rust::jsg {
using Isolate = v8::Isolate;
using FunctionCallbackInfo = v8::FunctionCallbackInfo<v8::Value>;
struct ModuleRegistry;
struct Local;
struct Global;
struct Realm;
struct GcVisitor;
enum class ExceptionType : ::std::uint8_t;
// ModuleType enum is generated by CXX in v8.rs.h - forward declare it here
enum class ModuleType : ::std::uint8_t;
using ModuleCallback = ::rust::Fn<Local(Isolate*)>;

// Mirrors the CXX shared struct defined in v8.rs. Must be kept in sync.
// The CXX-generated v8.rs.h provides the canonical definition; this is
// only used when ffi.h is included before v8.rs.h (e.g. from ffi.c++
// before the CXX bridge is compiled).
#ifndef CXXBRIDGE1_STRUCT_workerd$rust$jsg$TraitObjectPtr
#define CXXBRIDGE1_STRUCT_workerd$rust$jsg$TraitObjectPtr
struct TraitObjectPtr {
  uintptr_t data_ptr = 0;
  uintptr_t vtable_ptr = 0;
  uintptr_t type_id_lo = 0;
  uintptr_t type_id_hi = 0;
};
#endif

// A Wrappable subclass for Rust objects.
//
// Lives on the KJ heap (via kj::Refcounted through Wrappable) and integrates
// with cppgc via the CppgcShim bridge pattern that Wrappable provides.
//
// The data[] field stores a Rust fat pointer (data + vtable) to `dyn GarbageCollected`
// from a leaked Box<dyn GarbageCollected>. This lets us call back into Rust for tracing
// and destruction without knowing the concrete type at compile time.
class Wrappable: public ::workerd::jsg::Wrappable {
 public:
  ~Wrappable();
  void jsgVisitForGc(::workerd::jsg::GcVisitor& visitor) override;
  kj::StringPtr jsgGetMemoryName() const override;
  size_t jsgGetMemorySelfSize() const override;

  // Cached memory name from Rust GarbageCollected::get_name().
  // Populated lazily by jsgGetMemoryName().
  mutable kj::Maybe<kj::String> memoryName;

  // Returns a new kj::Rc reference to this Wrappable.
  kj::Rc<Wrappable> toRc() {
    return addRefToThis();
  }

  // Rust trait object pointer + TypeId, stored by Ref::new().
  // Defined as a CXX shared struct in v8.rs; contains data_ptr, vtable_ptr,
  // type_id_lo, type_id_hi.
  TraitObjectPtr trait_object = {0, 0, 0, 0};
};

struct ResourceDescriptor;

// Wrappable lifecycle — returns KjRc<Wrappable> to Rust for reference-counted ownership.
// Ref::clone calls wrappable_add_strong_ref; Ref::drop calls wrappable_remove_strong_ref.
// wrappable_remove_strong_ref does addRef(+1) + maybeDeferDestruction(-1) = net 0 on kj::Rc;
// the actual kj::Rc decrement happens when WrappableRc (KjRc<Wrappable>) is dropped.
kj::Rc<Wrappable> wrappable_new(TraitObjectPtr ptr);
kj::Rc<Wrappable> wrappable_to_rc(Wrappable& wrappable);
void wrappable_add_strong_ref(Wrappable& wrappable);
void wrappable_remove_strong_ref(Wrappable& wrappable, bool is_strong);
void wrappable_visit_ref(
    Wrappable& wrappable, uintptr_t* ref_parent, bool* ref_strong, GcVisitor* visitor);

// Function declarations
void local_drop(Local value);
Local local_clone(const Local& value);
Global local_to_global(Isolate* isolate, Local value);
Local local_new_number(Isolate* isolate, double value);
Local local_new_string(Isolate* isolate, ::rust::Str value);
Local local_new_boolean(Isolate* isolate, bool value);
Local local_new_object(Isolate* isolate);
Local local_new_null(Isolate* isolate);
Local local_new_undefined(Isolate* isolate);
Local local_new_array(Isolate* isolate, size_t length);
Local local_new_uint8_array(Isolate* isolate, const uint8_t* data, size_t length);
Local local_new_uint16_array(Isolate* isolate, const uint16_t* data, size_t length);
Local local_new_uint32_array(Isolate* isolate, const uint32_t* data, size_t length);
Local local_new_int8_array(Isolate* isolate, const int8_t* data, size_t length);
Local local_new_int16_array(Isolate* isolate, const int16_t* data, size_t length);
Local local_new_int32_array(Isolate* isolate, const int32_t* data, size_t length);
Local local_new_float32_array(Isolate* isolate, const float* data, size_t length);
Local local_new_float64_array(Isolate* isolate, const double* data, size_t length);
Local local_new_bigint64_array(Isolate* isolate, const int64_t* data, size_t length);
Local local_new_biguint64_array(Isolate* isolate, const uint64_t* data, size_t length);
bool local_eq(const Local& lhs, const Local& rhs);
bool local_has_value(const Local& val);
bool local_is_string(const Local& val);
bool local_is_boolean(const Local& val);
bool local_is_number(const Local& val);
bool local_is_null(const Local& val);
bool local_is_undefined(const Local& val);
bool local_is_null_or_undefined(const Local& val);
bool local_is_object(const Local& val);
bool local_is_native_error(const Local& val);
bool local_is_array(const Local& val);
bool local_is_uint8_array(const Local& val);
bool local_is_uint16_array(const Local& val);
bool local_is_uint32_array(const Local& val);
bool local_is_int8_array(const Local& val);
bool local_is_int16_array(const Local& val);
bool local_is_int32_array(const Local& val);
bool local_is_float32_array(const Local& val);
bool local_is_float64_array(const Local& val);
bool local_is_bigint64_array(const Local& val);
bool local_is_biguint64_array(const Local& val);
bool local_is_array_buffer(const Local& val);
bool local_is_array_buffer_view(const Local& val);
bool local_is_function(const Local& val);
::rust::String local_type_of(Isolate* isolate, const Local& val);

// Local<Function>
Local local_function_call(
    Isolate* isolate, const Local& function, const Local& recv, ::rust::Slice<const Local> args);

// Local<Object>
void local_object_set_property(Isolate* isolate, Local& object, ::rust::Str key, Local value);
bool local_object_has_property(Isolate* isolate, const Local& object, ::rust::Str key);
kj::Maybe<Local> local_object_get_property(Isolate* isolate, const Local& object, ::rust::Str key);

// Local<Array>
uint32_t local_array_length(Isolate* isolate, const Local& array);
Local local_array_get(Isolate* isolate, const Local& array, uint32_t index);
void local_array_set(Isolate* isolate, Local& array, uint32_t index, Local value);
::rust::Vec<Global> local_array_iterate(Isolate* isolate, Local value);

// Local<TypedArray>
size_t local_typed_array_length(Isolate* isolate, const Local& array);
uint8_t local_uint8_array_get(Isolate* isolate, const Local& array, size_t index);
uint16_t local_uint16_array_get(Isolate* isolate, const Local& array, size_t index);
uint32_t local_uint32_array_get(Isolate* isolate, const Local& array, size_t index);
int8_t local_int8_array_get(Isolate* isolate, const Local& array, size_t index);
int16_t local_int16_array_get(Isolate* isolate, const Local& array, size_t index);
int32_t local_int32_array_get(Isolate* isolate, const Local& array, size_t index);
float local_float32_array_get(Isolate* isolate, const Local& array, size_t index);
double local_float64_array_get(Isolate* isolate, const Local& array, size_t index);
int64_t local_bigint64_array_get(Isolate* isolate, const Local& array, size_t index);
uint64_t local_biguint64_array_get(Isolate* isolate, const Local& array, size_t index);

// Global<T>
void global_reset(Global& value);
Global global_clone(Isolate* isolate, const Global& value);
Local global_to_local(Isolate* isolate, const Global& value);

// Wrappable - data access
const TraitObjectPtr& wrappable_get_trait_object(const Wrappable& wrappable);
void wrappable_clear_trait_object(Wrappable& wrappable);
kj::uint wrappable_strong_refcount(const Wrappable& wrappable);

// Wrappers
Local wrap_resource(Isolate* isolate, kj::Rc<Wrappable> wrappable, const Global& tmpl);

// Unwrappers
::rust::String unwrap_string(Isolate* isolate, Local value);
bool unwrap_boolean(Isolate* isolate, Local value);
double unwrap_number(Isolate* isolate, Local value);
kj::Rc<Wrappable> unwrap_resource(Isolate* isolate, Local value);
::rust::Vec<uint8_t> unwrap_uint8_array(Isolate* isolate, Local value);
::rust::Vec<uint16_t> unwrap_uint16_array(Isolate* isolate, Local value);
::rust::Vec<uint32_t> unwrap_uint32_array(Isolate* isolate, Local value);
::rust::Vec<int8_t> unwrap_int8_array(Isolate* isolate, Local value);
::rust::Vec<int16_t> unwrap_int16_array(Isolate* isolate, Local value);
::rust::Vec<int32_t> unwrap_int32_array(Isolate* isolate, Local value);
::rust::Vec<float> unwrap_float32_array(Isolate* isolate, Local value);
::rust::Vec<double> unwrap_float64_array(Isolate* isolate, Local value);
::rust::Vec<int64_t> unwrap_bigint64_array(Isolate* isolate, Local value);
::rust::Vec<uint64_t> unwrap_biguint64_array(Isolate* isolate, Local value);

// FunctionCallbackInfo
Isolate* fci_get_isolate(FunctionCallbackInfo* args);
Local fci_get_this(FunctionCallbackInfo* args);
size_t fci_get_length(FunctionCallbackInfo* args);
Local fci_get_arg(FunctionCallbackInfo* args, size_t index);
void fci_set_return_value(FunctionCallbackInfo* args, Local value);

struct ModuleRegistry {
  virtual ~ModuleRegistry() = default;
  virtual void addBuiltinModule(
      ::rust::Str specifier, ModuleCallback moduleCallback, ModuleType moduleType) = 0;
};

inline void register_add_builtin_module(ModuleRegistry& registry,
    ::rust::Str specifier,
    ModuleCallback callback,
    ModuleType moduleType) {
  registry.addBuiltinModule(specifier, kj::mv(callback), moduleType);
}

Global create_resource_template(Isolate* isolate, const ResourceDescriptor& descriptor);

// FunctionTemplate
Local function_template_get_function(Isolate* isolate, const Global& tmpl);

// Realm
Realm* realm_from_isolate(Isolate* isolate);

// Errors
Local exception_create(Isolate* isolate, ExceptionType exception_type, ::rust::Str message);

// Isolate
void isolate_throw_exception(Isolate* isolate, Local exception);
void isolate_throw_error(Isolate* isolate, ::rust::Str message);
bool isolate_is_locked(Isolate* isolate);

}  // namespace workerd::rust::jsg
