load("@rules_rust//rust:defs.bzl", "rust_library", "rust_unpretty")
load("//:build/wd_cc_library.bzl", "wd_cc_library")
load("//:build/wd_rust_test.bzl", "wd_rust_test")
load("//src/rust/cxx/tools/bazel:rust_cxx_bridge.bzl", "rust_cxx_bridge")

wd_rust_test(
    name = "test",
    size = "small",
    srcs = ["test.rs"],
    edition = "2024",
    deps = [
        ":cxx_test_suite",
        "//src/rust/cxx",
    ],
)

wd_rust_test(
    name = "cxx_gen_test",
    size = "small",
    srcs = ["cxx_gen.rs"],
    edition = "2024",
    deps = [
        ":cxx_test_suite",
        "//src/rust/cxx",
        "//src/rust/cxx:cxx-gen",
    ],
)

rust_library(
    name = "cxx_test_suite",
    testonly = True,
    srcs = [
        "ffi/cast.rs",
        "ffi/lib.rs",
        "ffi/module.rs",
    ],
    edition = "2024",
    link_deps = [
        ":impl",
    ],
    proc_macro_deps = [
        "//src/rust/cxx:cxxbridge-macro",
    ],
    target_compatible_with = select({
        "@//build/config:no_build": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "//src/rust/cxx",
        "//src/rust/cxx/kj-rs",
    ],
)

wd_cc_library(
    name = "jsg-mock",
    hdrs = ["ffi/jsg.h"],
    include_prefix = "workerd/jsg",
    strip_include_prefix = "ffi",
)

wd_cc_library(
    name = "impl",
    testonly = True,
    srcs = [
        "ffi/tests.cc",
        ":bridge/source",
        ":module/source",
        "//src/rust/cxx/kj-rs:bridge/source",
    ],
    hdrs = ["ffi/tests.h"],
    linkstatic = True,
    strip_include_prefix = "/src/rust/cxx",
    deps = [
        ":bridge/include",
        ":jsg-mock",
        ":module/include",
        "//src/rust/cxx:core",
        "//src/rust/cxx/kj-rs:bridge/include",
        "//src/rust/cxx/kj-rs:kj-rs-lib",
    ],
)

rust_cxx_bridge(
    name = "bridge",
    testonly = True,
    src = "ffi/lib.rs",
    hdrs = ["ffi/tests.h"],
    strip_include_prefix = "/src/rust/cxx",
    deps = [
        ":jsg-mock",
        ":module",
        "//src/rust/cxx:core",
        "//src/rust/cxx/kj-rs:kj-rs-lib",
    ],
)

rust_unpretty(
    name = "expand",
    testonly = True,
    tags = [
        "manual",
        "off-by-default",
    ],
    deps = [
        ":cxx_test_suite",
    ],
)

rust_cxx_bridge(
    name = "module",
    testonly = True,
    src = "ffi/module.rs",
    hdrs = ["ffi/tests.h"],
    strip_include_prefix = "/src/rust/cxx",
    deps = [
        "//src/rust/cxx:core",
    ],
)
