// More beautiful numbers
const NGHTTP2_ERR_FRAME_SIZE_ERROR = -522
const NGHTTP2_SESSION_SERVER = 0
const NGHTTP2_SESSION_CLIENT = 1
const NGHTTP2_STREAM_STATE_IDLE = 1
const NGHTTP2_STREAM_STATE_OPEN = 2
const NGHTTP2_STREAM_STATE_RESERVED_LOCAL = 3
const NGHTTP2_STREAM_STATE_RESERVED_REMOTE = 4
const NGHTTP2_STREAM_STATE_HALF_CLOSED_LOCAL = 5
const NGHTTP2_STREAM_STATE_HALF_CLOSED_REMOTE = 6
const NGHTTP2_STREAM_STATE_CLOSED = 7
const NGHTTP2_FLAG_NONE = 0
const NGHTTP2_FLAG_END_STREAM = 1
const NGHTTP2_FLAG_END_HEADERS = 4
const NGHTTP2_FLAG_ACK = 1
const NGHTTP2_FLAG_PADDED = 8
const NGHTTP2_FLAG_PRIORITY = 32
const DEFAULT_SETTINGS_HEADER_TABLE_SIZE = 4096
const DEFAULT_SETTINGS_ENABLE_PUSH = 1
const DEFAULT_SETTINGS_MAX_CONCURRENT_STREAMS = 4_294_967_295
const DEFAULT_SETTINGS_INITIAL_WINDOW_SIZE = 65_535
const DEFAULT_SETTINGS_MAX_FRAME_SIZE = 16_384
const DEFAULT_SETTINGS_MAX_HEADER_LIST_SIZE = 65_535
const DEFAULT_SETTINGS_ENABLE_CONNECT_PROTOCOL = 0
const MAX_MAX_FRAME_SIZE = 16_777_215
const MIN_MAX_FRAME_SIZE = 16_384
const MAX_INITIAL_WINDOW_SIZE = 2_147_483_647
const NGHTTP2_SETTINGS_HEADER_TABLE_SIZE = 1
const NGHTTP2_SETTINGS_ENABLE_PUSH = 2
const NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS = 3
const NGHTTP2_SETTINGS_INITIAL_WINDOW_SIZE = 4
const NGHTTP2_SETTINGS_MAX_FRAME_SIZE = 5
const NGHTTP2_SETTINGS_MAX_HEADER_LIST_SIZE = 6
const NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL = 8
const PADDING_STRATEGY_NONE = 0
const PADDING_STRATEGY_ALIGNED = 1
const PADDING_STRATEGY_MAX = 2
const PADDING_STRATEGY_CALLBACK = 1
const NGHTTP2_NO_ERROR = 0
const NGHTTP2_PROTOCOL_ERROR = 1
const NGHTTP2_INTERNAL_ERROR = 2
const NGHTTP2_FLOW_CONTROL_ERROR = 3
const NGHTTP2_SETTINGS_TIMEOUT = 4
const NGHTTP2_STREAM_CLOSED = 5
const NGHTTP2_FRAME_SIZE_ERROR = 6
const NGHTTP2_REFUSED_STREAM = 7
const NGHTTP2_CANCEL = 8
const NGHTTP2_COMPRESSION_ERROR = 9
const NGHTTP2_CONNECT_ERROR = 10
const NGHTTP2_ENHANCE_YOUR_CALM = 11
const NGHTTP2_INADEQUATE_SECURITY = 12
const NGHTTP2_HTTP_1_1_REQUIRED = 13
const NGHTTP2_DEFAULT_WEIGHT = 16
const HTTP2_HEADER_STATUS = ':status'
const HTTP2_HEADER_METHOD = ':method'
const HTTP2_HEADER_AUTHORITY = ':authority'
const HTTP2_HEADER_SCHEME = ':scheme'
const HTTP2_HEADER_PATH = ':path'
const HTTP2_HEADER_PROTOCOL = ':protocol'
const HTTP2_HEADER_ACCEPT_ENCODING = 'accept-encoding'
const HTTP2_HEADER_ACCEPT_LANGUAGE = 'accept-language'
const HTTP2_HEADER_ACCEPT_RANGES = 'accept-ranges'
const HTTP2_HEADER_ACCEPT = 'accept'
const HTTP2_HEADER_ACCESS_CONTROL_ALLOW_CREDENTIALS =
  'access-control-allow-credentials'
const HTTP2_HEADER_ACCESS_CONTROL_ALLOW_HEADERS = 'access-control-allow-headers'
const HTTP2_HEADER_ACCESS_CONTROL_ALLOW_METHODS = 'access-control-allow-methods'
const HTTP2_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN = 'access-control-allow-origin'
const HTTP2_HEADER_ACCESS_CONTROL_EXPOSE_HEADERS =
  'access-control-expose-headers'
const HTTP2_HEADER_ACCESS_CONTROL_REQUEST_HEADERS =
  'access-control-request-headers'
const HTTP2_HEADER_ACCESS_CONTROL_REQUEST_METHOD =
  'access-control-request-method'
const HTTP2_HEADER_AGE = 'age'
const HTTP2_HEADER_AUTHORIZATION = 'authorization'
const HTTP2_HEADER_CACHE_CONTROL = 'cache-control'
const HTTP2_HEADER_CONNECTION = 'connection'
const HTTP2_HEADER_CONTENT_DISPOSITION = 'content-disposition'
const HTTP2_HEADER_CONTENT_ENCODING = 'content-encoding'
const HTTP2_HEADER_CONTENT_LENGTH = 'content-length'
const HTTP2_HEADER_CONTENT_TYPE = 'content-type'
const HTTP2_HEADER_COOKIE = 'cookie'
const HTTP2_HEADER_DATE = 'date'
const HTTP2_HEADER_ETAG = 'etag'
const HTTP2_HEADER_FORWARDED = 'forwarded'
const HTTP2_HEADER_HOST = 'host'
const HTTP2_HEADER_IF_MODIFIED_SINCE = 'if-modified-since'
const HTTP2_HEADER_IF_NONE_MATCH = 'if-none-match'
const HTTP2_HEADER_IF_RANGE = 'if-range'
const HTTP2_HEADER_LAST_MODIFIED = 'last-modified'
const HTTP2_HEADER_LINK = 'link'
const HTTP2_HEADER_LOCATION = 'location'
const HTTP2_HEADER_RANGE = 'range'
const HTTP2_HEADER_REFERER = 'referer'
const HTTP2_HEADER_SERVER = 'server'
const HTTP2_HEADER_SET_COOKIE = 'set-cookie'
const HTTP2_HEADER_STRICT_TRANSPORT_SECURITY = 'strict-transport-security'
const HTTP2_HEADER_TRANSFER_ENCODING = 'transfer-encoding'
const HTTP2_HEADER_TE = 'te'
const HTTP2_HEADER_UPGRADE_INSECURE_REQUESTS = 'upgrade-insecure-requests'
const HTTP2_HEADER_UPGRADE = 'upgrade'
const HTTP2_HEADER_USER_AGENT = 'user-agent'
const HTTP2_HEADER_VARY = 'vary'
const HTTP2_HEADER_X_CONTENT_TYPE_OPTIONS = 'x-content-type-options'
const HTTP2_HEADER_X_FRAME_OPTIONS = 'x-frame-options'
const HTTP2_HEADER_KEEP_ALIVE = 'keep-alive'
const HTTP2_HEADER_PROXY_CONNECTION = 'proxy-connection'
const HTTP2_HEADER_X_XSS_PROTECTION = 'x-xss-protection'
const HTTP2_HEADER_ALT_SVC = 'alt-svc'
const HTTP2_HEADER_CONTENT_SECURITY_POLICY = 'content-security-policy'
const HTTP2_HEADER_EARLY_DATA = 'early-data'
const HTTP2_HEADER_EXPECT_CT = 'expect-ct'
const HTTP2_HEADER_ORIGIN = 'origin'
const HTTP2_HEADER_PURPOSE = 'purpose'
const HTTP2_HEADER_TIMING_ALLOW_ORIGIN = 'timing-allow-origin'
const HTTP2_HEADER_X_FORWARDED_FOR = 'x-forwarded-for'
const HTTP2_HEADER_PRIORITY = 'priority'
const HTTP2_HEADER_ACCEPT_CHARSET = 'accept-charset'
const HTTP2_HEADER_ACCESS_CONTROL_MAX_AGE = 'access-control-max-age'
const HTTP2_HEADER_ALLOW = 'allow'
const HTTP2_HEADER_CONTENT_LANGUAGE = 'content-language'
const HTTP2_HEADER_CONTENT_LOCATION = 'content-location'
const HTTP2_HEADER_CONTENT_MD5 = 'content-md5'
const HTTP2_HEADER_CONTENT_RANGE = 'content-range'
const HTTP2_HEADER_DNT = 'dnt'
const HTTP2_HEADER_EXPECT = 'expect'
const HTTP2_HEADER_EXPIRES = 'expires'
const HTTP2_HEADER_FROM = 'from'
const HTTP2_HEADER_IF_MATCH = 'if-match'
const HTTP2_HEADER_IF_UNMODIFIED_SINCE = 'if-unmodified-since'
const HTTP2_HEADER_MAX_FORWARDS = 'max-forwards'
const HTTP2_HEADER_PREFER = 'prefer'
const HTTP2_HEADER_PROXY_AUTHENTICATE = 'proxy-authenticate'
const HTTP2_HEADER_PROXY_AUTHORIZATION = 'proxy-authorization'
const HTTP2_HEADER_REFRESH = 'refresh'
const HTTP2_HEADER_RETRY_AFTER = 'retry-after'
const HTTP2_HEADER_TRAILER = 'trailer'
const HTTP2_HEADER_TK = 'tk'
const HTTP2_HEADER_VIA = 'via'
const HTTP2_HEADER_WARNING = 'warning'
const HTTP2_HEADER_WWW_AUTHENTICATE = 'www-authenticate'
const HTTP2_HEADER_HTTP2_SETTINGS = 'http2-settings'
const HTTP2_METHOD_ACL = 'ACL'
const HTTP2_METHOD_BASELINE_CONTROL = 'BASELINE-CONTROL'
const HTTP2_METHOD_BIND = 'BIND'
const HTTP2_METHOD_CHECKIN = 'CHECKIN'
const HTTP2_METHOD_CHECKOUT = 'CHECKOUT'
const HTTP2_METHOD_CONNECT = 'CONNECT'
const HTTP2_METHOD_COPY = 'COPY'
const HTTP2_METHOD_DELETE = 'DELETE'
const HTTP2_METHOD_GET = 'GET'
const HTTP2_METHOD_HEAD = 'HEAD'
const HTTP2_METHOD_LABEL = 'LABEL'
const HTTP2_METHOD_LINK = 'LINK'
const HTTP2_METHOD_LOCK = 'LOCK'
const HTTP2_METHOD_MERGE = 'MERGE'
const HTTP2_METHOD_MKACTIVITY = 'MKACTIVITY'
const HTTP2_METHOD_MKCALENDAR = 'MKCALENDAR'
const HTTP2_METHOD_MKCOL = 'MKCOL'
const HTTP2_METHOD_MKREDIRECTREF = 'MKREDIRECTREF'
const HTTP2_METHOD_MKWORKSPACE = 'MKWORKSPACE'
const HTTP2_METHOD_MOVE = 'MOVE'
const HTTP2_METHOD_OPTIONS = 'OPTIONS'
const HTTP2_METHOD_ORDERPATCH = 'ORDERPATCH'
const HTTP2_METHOD_PATCH = 'PATCH'
const HTTP2_METHOD_POST = 'POST'
const HTTP2_METHOD_PRI = 'PRI'
const HTTP2_METHOD_PROPFIND = 'PROPFIND'
const HTTP2_METHOD_PROPPATCH = 'PROPPATCH'
const HTTP2_METHOD_PUT = 'PUT'
const HTTP2_METHOD_REBIND = 'REBIND'
const HTTP2_METHOD_REPORT = 'REPORT'
const HTTP2_METHOD_SEARCH = 'SEARCH'
const HTTP2_METHOD_TRACE = 'TRACE'
const HTTP2_METHOD_UNBIND = 'UNBIND'
const HTTP2_METHOD_UNCHECKOUT = 'UNCHECKOUT'
const HTTP2_METHOD_UNLINK = 'UNLINK'
const HTTP2_METHOD_UNLOCK = 'UNLOCK'
const HTTP2_METHOD_UPDATE = 'UPDATE'
const HTTP2_METHOD_UPDATEREDIRECTREF = 'UPDATEREDIRECTREF'
const HTTP2_METHOD_VERSION_CONTROL = 'VERSION-CONTROL'
const HTTP_STATUS_CONTINUE = 100
const HTTP_STATUS_SWITCHING_PROTOCOLS = 101
const HTTP_STATUS_PROCESSING = 102
const HTTP_STATUS_EARLY_HINTS = 103
const HTTP_STATUS_OK = 200
const HTTP_STATUS_CREATED = 201
const HTTP_STATUS_ACCEPTED = 202
const HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION = 203
const HTTP_STATUS_NO_CONTENT = 204
const HTTP_STATUS_RESET_CONTENT = 205
const HTTP_STATUS_PARTIAL_CONTENT = 206
const HTTP_STATUS_MULTI_STATUS = 207
const HTTP_STATUS_ALREADY_REPORTED = 208
const HTTP_STATUS_IM_USED = 226
const HTTP_STATUS_MULTIPLE_CHOICES = 300
const HTTP_STATUS_MOVED_PERMANENTLY = 301
const HTTP_STATUS_FOUND = 302
const HTTP_STATUS_SEE_OTHER = 303
const HTTP_STATUS_NOT_MODIFIED = 304
const HTTP_STATUS_USE_PROXY = 305
const HTTP_STATUS_TEMPORARY_REDIRECT = 307
const HTTP_STATUS_PERMANENT_REDIRECT = 308
const HTTP_STATUS_BAD_REQUEST = 400
const HTTP_STATUS_UNAUTHORIZED = 401
const HTTP_STATUS_PAYMENT_REQUIRED = 402
const HTTP_STATUS_FORBIDDEN = 403
const HTTP_STATUS_NOT_FOUND = 404
const HTTP_STATUS_METHOD_NOT_ALLOWED = 405
const HTTP_STATUS_NOT_ACCEPTABLE = 406
const HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED = 407
const HTTP_STATUS_REQUEST_TIMEOUT = 408
const HTTP_STATUS_CONFLICT = 409
const HTTP_STATUS_GONE = 410
const HTTP_STATUS_LENGTH_REQUIRED = 411
const HTTP_STATUS_PRECONDITION_FAILED = 412
const HTTP_STATUS_PAYLOAD_TOO_LARGE = 413
const HTTP_STATUS_URI_TOO_LONG = 414
const HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE = 415
const HTTP_STATUS_RANGE_NOT_SATISFIABLE = 416
const HTTP_STATUS_EXPECTATION_FAILED = 417
const HTTP_STATUS_TEAPOT = 418
const HTTP_STATUS_MISDIRECTED_REQUEST = 421
const HTTP_STATUS_UNPROCESSABLE_ENTITY = 422
const HTTP_STATUS_LOCKED = 423
const HTTP_STATUS_FAILED_DEPENDENCY = 424
const HTTP_STATUS_TOO_EARLY = 425
const HTTP_STATUS_UPGRADE_REQUIRED = 426
const HTTP_STATUS_PRECONDITION_REQUIRED = 428
const HTTP_STATUS_TOO_MANY_REQUESTS = 429
const HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
const HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS = 451
const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500
const HTTP_STATUS_NOT_IMPLEMENTED = 501
const HTTP_STATUS_BAD_GATEWAY = 502
const HTTP_STATUS_SERVICE_UNAVAILABLE = 503
const HTTP_STATUS_GATEWAY_TIMEOUT = 504
const HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED = 505
const HTTP_STATUS_VARIANT_ALSO_NEGOTIATES = 506
const HTTP_STATUS_INSUFFICIENT_STORAGE = 507
const HTTP_STATUS_LOOP_DETECTED = 508
const HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED = 509
const HTTP_STATUS_NOT_EXTENDED = 510
const HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED = 511

export const constants = {
  NGHTTP2_ERR_FRAME_SIZE_ERROR,
  NGHTTP2_SESSION_SERVER,
  NGHTTP2_SESSION_CLIENT,
  NGHTTP2_STREAM_STATE_IDLE,
  NGHTTP2_STREAM_STATE_OPEN,
  NGHTTP2_STREAM_STATE_RESERVED_LOCAL,
  NGHTTP2_STREAM_STATE_RESERVED_REMOTE,
  NGHTTP2_STREAM_STATE_HALF_CLOSED_LOCAL,
  NGHTTP2_STREAM_STATE_HALF_CLOSED_REMOTE,
  NGHTTP2_STREAM_STATE_CLOSED,
  NGHTTP2_FLAG_NONE,
  NGHTTP2_FLAG_END_STREAM,
  NGHTTP2_FLAG_END_HEADERS,
  NGHTTP2_FLAG_ACK,
  NGHTTP2_FLAG_PADDED,
  NGHTTP2_FLAG_PRIORITY,
  DEFAULT_SETTINGS_HEADER_TABLE_SIZE,
  DEFAULT_SETTINGS_ENABLE_PUSH,
  DEFAULT_SETTINGS_MAX_CONCURRENT_STREAMS,
  DEFAULT_SETTINGS_INITIAL_WINDOW_SIZE,
  DEFAULT_SETTINGS_MAX_FRAME_SIZE,
  DEFAULT_SETTINGS_MAX_HEADER_LIST_SIZE,
  DEFAULT_SETTINGS_ENABLE_CONNECT_PROTOCOL,
  MAX_MAX_FRAME_SIZE,
  MIN_MAX_FRAME_SIZE,
  MAX_INITIAL_WINDOW_SIZE,
  NGHTTP2_SETTINGS_HEADER_TABLE_SIZE,
  NGHTTP2_SETTINGS_ENABLE_PUSH,
  NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS,
  NGHTTP2_SETTINGS_INITIAL_WINDOW_SIZE,
  NGHTTP2_SETTINGS_MAX_FRAME_SIZE,
  NGHTTP2_SETTINGS_MAX_HEADER_LIST_SIZE,
  NGHTTP2_SETTINGS_ENABLE_CONNECT_PROTOCOL,
  PADDING_STRATEGY_NONE,
  PADDING_STRATEGY_ALIGNED,
  PADDING_STRATEGY_MAX,
  PADDING_STRATEGY_CALLBACK,
  NGHTTP2_NO_ERROR,
  NGHTTP2_PROTOCOL_ERROR,
  NGHTTP2_INTERNAL_ERROR,
  NGHTTP2_FLOW_CONTROL_ERROR,
  NGHTTP2_SETTINGS_TIMEOUT,
  NGHTTP2_STREAM_CLOSED,
  NGHTTP2_FRAME_SIZE_ERROR,
  NGHTTP2_REFUSED_STREAM,
  NGHTTP2_CANCEL,
  NGHTTP2_COMPRESSION_ERROR,
  NGHTTP2_CONNECT_ERROR,
  NGHTTP2_ENHANCE_YOUR_CALM,
  NGHTTP2_INADEQUATE_SECURITY,
  NGHTTP2_HTTP_1_1_REQUIRED,
  NGHTTP2_DEFAULT_WEIGHT,
  HTTP2_HEADER_STATUS,
  HTTP2_HEADER_METHOD,
  HTTP2_HEADER_AUTHORITY,
  HTTP2_HEADER_SCHEME,
  HTTP2_HEADER_PATH,
  HTTP2_HEADER_PROTOCOL,
  HTTP2_HEADER_ACCEPT_ENCODING,
  HTTP2_HEADER_ACCEPT_LANGUAGE,
  HTTP2_HEADER_ACCEPT_RANGES,
  HTTP2_HEADER_ACCEPT,
  HTTP2_HEADER_ACCESS_CONTROL_ALLOW_CREDENTIALS,
  HTTP2_HEADER_ACCESS_CONTROL_ALLOW_HEADERS,
  HTTP2_HEADER_ACCESS_CONTROL_ALLOW_METHODS,
  HTTP2_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN,
  HTTP2_HEADER_ACCESS_CONTROL_EXPOSE_HEADERS,
  HTTP2_HEADER_ACCESS_CONTROL_REQUEST_HEADERS,
  HTTP2_HEADER_ACCESS_CONTROL_REQUEST_METHOD,
  HTTP2_HEADER_AGE,
  HTTP2_HEADER_AUTHORIZATION,
  HTTP2_HEADER_CACHE_CONTROL,
  HTTP2_HEADER_CONNECTION,
  HTTP2_HEADER_CONTENT_DISPOSITION,
  HTTP2_HEADER_CONTENT_ENCODING,
  HTTP2_HEADER_CONTENT_LENGTH,
  HTTP2_HEADER_CONTENT_TYPE,
  HTTP2_HEADER_COOKIE,
  HTTP2_HEADER_DATE,
  HTTP2_HEADER_ETAG,
  HTTP2_HEADER_FORWARDED,
  HTTP2_HEADER_HOST,
  HTTP2_HEADER_IF_MODIFIED_SINCE,
  HTTP2_HEADER_IF_NONE_MATCH,
  HTTP2_HEADER_IF_RANGE,
  HTTP2_HEADER_LAST_MODIFIED,
  HTTP2_HEADER_LINK,
  HTTP2_HEADER_LOCATION,
  HTTP2_HEADER_RANGE,
  HTTP2_HEADER_REFERER,
  HTTP2_HEADER_SERVER,
  HTTP2_HEADER_SET_COOKIE,
  HTTP2_HEADER_STRICT_TRANSPORT_SECURITY,
  HTTP2_HEADER_TRANSFER_ENCODING,
  HTTP2_HEADER_TE,
  HTTP2_HEADER_UPGRADE_INSECURE_REQUESTS,
  HTTP2_HEADER_UPGRADE,
  HTTP2_HEADER_USER_AGENT,
  HTTP2_HEADER_VARY,
  HTTP2_HEADER_X_CONTENT_TYPE_OPTIONS,
  HTTP2_HEADER_X_FRAME_OPTIONS,
  HTTP2_HEADER_KEEP_ALIVE,
  HTTP2_HEADER_PROXY_CONNECTION,
  HTTP2_HEADER_X_XSS_PROTECTION,
  HTTP2_HEADER_ALT_SVC,
  HTTP2_HEADER_CONTENT_SECURITY_POLICY,
  HTTP2_HEADER_EARLY_DATA,
  HTTP2_HEADER_EXPECT_CT,
  HTTP2_HEADER_ORIGIN,
  HTTP2_HEADER_PURPOSE,
  HTTP2_HEADER_TIMING_ALLOW_ORIGIN,
  HTTP2_HEADER_X_FORWARDED_FOR,
  HTTP2_HEADER_PRIORITY,
  HTTP2_HEADER_ACCEPT_CHARSET,
  HTTP2_HEADER_ACCESS_CONTROL_MAX_AGE,
  HTTP2_HEADER_ALLOW,
  HTTP2_HEADER_CONTENT_LANGUAGE,
  HTTP2_HEADER_CONTENT_LOCATION,
  HTTP2_HEADER_CONTENT_MD5,
  HTTP2_HEADER_CONTENT_RANGE,
  HTTP2_HEADER_DNT,
  HTTP2_HEADER_EXPECT,
  HTTP2_HEADER_EXPIRES,
  HTTP2_HEADER_FROM,
  HTTP2_HEADER_IF_MATCH,
  HTTP2_HEADER_IF_UNMODIFIED_SINCE,
  HTTP2_HEADER_MAX_FORWARDS,
  HTTP2_HEADER_PREFER,
  HTTP2_HEADER_PROXY_AUTHENTICATE,
  HTTP2_HEADER_PROXY_AUTHORIZATION,
  HTTP2_HEADER_REFRESH,
  HTTP2_HEADER_RETRY_AFTER,
  HTTP2_HEADER_TRAILER,
  HTTP2_HEADER_TK,
  HTTP2_HEADER_VIA,
  HTTP2_HEADER_WARNING,
  HTTP2_HEADER_WWW_AUTHENTICATE,
  HTTP2_HEADER_HTTP2_SETTINGS,
  HTTP2_METHOD_ACL,
  HTTP2_METHOD_BASELINE_CONTROL,
  HTTP2_METHOD_BIND,
  HTTP2_METHOD_CHECKIN,
  HTTP2_METHOD_CHECKOUT,
  HTTP2_METHOD_CONNECT,
  HTTP2_METHOD_COPY,
  HTTP2_METHOD_DELETE,
  HTTP2_METHOD_GET,
  HTTP2_METHOD_HEAD,
  HTTP2_METHOD_LABEL,
  HTTP2_METHOD_LINK,
  HTTP2_METHOD_LOCK,
  HTTP2_METHOD_MERGE,
  HTTP2_METHOD_MKACTIVITY,
  HTTP2_METHOD_MKCALENDAR,
  HTTP2_METHOD_MKCOL,
  HTTP2_METHOD_MKREDIRECTREF,
  HTTP2_METHOD_MKWORKSPACE,
  HTTP2_METHOD_MOVE,
  HTTP2_METHOD_OPTIONS,
  HTTP2_METHOD_ORDERPATCH,
  HTTP2_METHOD_PATCH,
  HTTP2_METHOD_POST,
  HTTP2_METHOD_PRI,
  HTTP2_METHOD_PROPFIND,
  HTTP2_METHOD_PROPPATCH,
  HTTP2_METHOD_PUT,
  HTTP2_METHOD_REBIND,
  HTTP2_METHOD_REPORT,
  HTTP2_METHOD_SEARCH,
  HTTP2_METHOD_TRACE,
  HTTP2_METHOD_UNBIND,
  HTTP2_METHOD_UNCHECKOUT,
  HTTP2_METHOD_UNLINK,
  HTTP2_METHOD_UNLOCK,
  HTTP2_METHOD_UPDATE,
  HTTP2_METHOD_UPDATEREDIRECTREF,
  HTTP2_METHOD_VERSION_CONTROL,
  HTTP_STATUS_CONTINUE,
  HTTP_STATUS_SWITCHING_PROTOCOLS,
  HTTP_STATUS_PROCESSING,
  HTTP_STATUS_EARLY_HINTS,
  HTTP_STATUS_OK,
  HTTP_STATUS_CREATED,
  HTTP_STATUS_ACCEPTED,
  HTTP_STATUS_NON_AUTHORITATIVE_INFORMATION,
  HTTP_STATUS_NO_CONTENT,
  HTTP_STATUS_RESET_CONTENT,
  HTTP_STATUS_PARTIAL_CONTENT,
  HTTP_STATUS_MULTI_STATUS,
  HTTP_STATUS_ALREADY_REPORTED,
  HTTP_STATUS_IM_USED,
  HTTP_STATUS_MULTIPLE_CHOICES,
  HTTP_STATUS_MOVED_PERMANENTLY,
  HTTP_STATUS_FOUND,
  HTTP_STATUS_SEE_OTHER,
  HTTP_STATUS_NOT_MODIFIED,
  HTTP_STATUS_USE_PROXY,
  HTTP_STATUS_TEMPORARY_REDIRECT,
  HTTP_STATUS_PERMANENT_REDIRECT,
  HTTP_STATUS_BAD_REQUEST,
  HTTP_STATUS_UNAUTHORIZED,
  HTTP_STATUS_PAYMENT_REQUIRED,
  HTTP_STATUS_FORBIDDEN,
  HTTP_STATUS_NOT_FOUND,
  HTTP_STATUS_METHOD_NOT_ALLOWED,
  HTTP_STATUS_NOT_ACCEPTABLE,
  HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED,
  HTTP_STATUS_REQUEST_TIMEOUT,
  HTTP_STATUS_CONFLICT,
  HTTP_STATUS_GONE,
  HTTP_STATUS_LENGTH_REQUIRED,
  HTTP_STATUS_PRECONDITION_FAILED,
  HTTP_STATUS_PAYLOAD_TOO_LARGE,
  HTTP_STATUS_URI_TOO_LONG,
  HTTP_STATUS_UNSUPPORTED_MEDIA_TYPE,
  HTTP_STATUS_RANGE_NOT_SATISFIABLE,
  HTTP_STATUS_EXPECTATION_FAILED,
  HTTP_STATUS_TEAPOT,
  HTTP_STATUS_MISDIRECTED_REQUEST,
  HTTP_STATUS_UNPROCESSABLE_ENTITY,
  HTTP_STATUS_LOCKED,
  HTTP_STATUS_FAILED_DEPENDENCY,
  HTTP_STATUS_TOO_EARLY,
  HTTP_STATUS_UPGRADE_REQUIRED,
  HTTP_STATUS_PRECONDITION_REQUIRED,
  HTTP_STATUS_TOO_MANY_REQUESTS,
  HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE,
  HTTP_STATUS_UNAVAILABLE_FOR_LEGAL_REASONS,
  HTTP_STATUS_INTERNAL_SERVER_ERROR,
  HTTP_STATUS_NOT_IMPLEMENTED,
  HTTP_STATUS_BAD_GATEWAY,
  HTTP_STATUS_SERVICE_UNAVAILABLE,
  HTTP_STATUS_GATEWAY_TIMEOUT,
  HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED,
  HTTP_STATUS_VARIANT_ALSO_NEGOTIATES,
  HTTP_STATUS_INSUFFICIENT_STORAGE,
  HTTP_STATUS_LOOP_DETECTED,
  HTTP_STATUS_BANDWIDTH_LIMIT_EXCEEDED,
  HTTP_STATUS_NOT_EXTENDED,
  HTTP_STATUS_NETWORK_AUTHENTICATION_REQUIRED,
}

for (const key of Object.keys(constants)) {
  Object.defineProperty(constants, key, { writable: false })
}
