// Copyright (c) 2017-2022 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0

import path from 'node:path';
import { getBindingPath } from 'harness/common';
import { type TestRunnerConfig } from 'harness/harness';

function loadWptResource(relativePath: string): void {
  const bindingPath = getBindingPath(
    path.dirname(globalThis.state.testFileName),
    relativePath
  );
  const code = globalThis.state.env[bindingPath];
  if (typeof code !== 'string') {
    throw new Error(
      `Test file ${bindingPath} not found. Update wpt_test.bzl to handle this case.`
    );
  }
  globalThis.state.env.unsafe.eval(code);
}

export default {
  'api-basics.any.js': {},
  'api-invalid-label.any.js': {},
  'api-replacement-encodings.any.js': {},
  'api-surrogates-utf8.any.js': {},
  'encodeInto.any.js': {
    comment: 'Requires MessageChannel.postMessage transfer list support',
    expectedFailures: ['encodeInto() and a detached output buffer'],
  },
  'idlharness.any.js': {
    comment:
      'Workers expose globals differently than browsers - these interface tests fail',
    expectedFailures: [
      'TextDecoder interface: existence and properties of interface object',
      'TextDecoder interface object length',
      'TextDecoder interface object name',
      'TextDecoder interface: existence and properties of interface prototype object',
      'TextDecoder interface: existence and properties of interface prototype object\'s "constructor" property',
      "TextDecoder interface: existence and properties of interface prototype object's @@unscopables property",
      'TextDecoder interface: operation decode(optional AllowSharedBufferSource, optional TextDecodeOptions)',
      'TextDecoder interface: attribute encoding',
      'TextDecoder interface: attribute fatal',
      'TextDecoder interface: attribute ignoreBOM',
      'TextDecoder must be primary interface of new TextDecoder()',
      'Stringification of new TextDecoder()',
      'TextDecoder interface: new TextDecoder() must inherit property "decode(optional AllowSharedBufferSource, optional TextDecodeOptions)" with the proper type',
      'TextDecoder interface: calling decode(optional AllowSharedBufferSource, optional TextDecodeOptions) on new TextDecoder() with too few arguments must throw TypeError',
      'TextDecoder interface: new TextDecoder() must inherit property "encoding" with the proper type',
      'TextDecoder interface: new TextDecoder() must inherit property "fatal" with the proper type',
      'TextDecoder interface: new TextDecoder() must inherit property "ignoreBOM" with the proper type',
      'TextEncoder interface: existence and properties of interface object',
      'TextEncoder interface object length',
      'TextEncoder interface object name',
      'TextEncoder interface: existence and properties of interface prototype object',
      'TextEncoder interface: existence and properties of interface prototype object\'s "constructor" property',
      "TextEncoder interface: existence and properties of interface prototype object's @@unscopables property",
      'TextEncoder interface: operation encode(optional USVString)',
      'TextEncoder interface: operation encodeInto(USVString, Uint8Array)',
      'TextEncoder interface: attribute encoding',
      'TextEncoder must be primary interface of new TextEncoder()',
      'Stringification of new TextEncoder()',
      'TextEncoder interface: new TextEncoder() must inherit property "encode(optional USVString)" with the proper type',
      'TextEncoder interface: calling encode(optional USVString) on new TextEncoder() with too few arguments must throw TypeError',
      'TextEncoder interface: new TextEncoder() must inherit property "encodeInto(USVString, Uint8Array)" with the proper type',
      'TextEncoder interface: calling encodeInto(USVString, Uint8Array) on new TextEncoder() with too few arguments must throw TypeError',
      'TextEncoder interface: new TextEncoder() must inherit property "encoding" with the proper type',
      'TextDecoderStream interface: existence and properties of interface object',
      'TextDecoderStream interface object length',
      'TextDecoderStream interface object name',
      'TextDecoderStream interface: existence and properties of interface prototype object',
      'TextDecoderStream interface: existence and properties of interface prototype object\'s "constructor" property',
      "TextDecoderStream interface: existence and properties of interface prototype object's @@unscopables property",
      'TextDecoderStream interface: attribute encoding',
      'TextDecoderStream interface: attribute fatal',
      'TextDecoderStream interface: attribute ignoreBOM',
      'TextEncoderStream interface: existence and properties of interface object',
      'TextEncoderStream interface object length',
      'TextEncoderStream interface object name',
      'TextEncoderStream interface: existence and properties of interface prototype object',
      'TextEncoderStream interface: existence and properties of interface prototype object\'s "constructor" property',
      "TextEncoderStream interface: existence and properties of interface prototype object's @@unscopables property",
      'TextEncoderStream interface: attribute encoding',
    ],
  },
  'iso-2022-jp-decoder.any.js': {},
  'legacy-mb-japanese/euc-jp/eucjp-decoder.js': {},
  'legacy-mb-japanese/euc-jp/eucjp-encoder.js': {
    before: (): void => {
      loadWptResource('./jis0208_index.js');
      loadWptResource('./jis0212_index.js');
    },
  },
  'legacy-mb-japanese/euc-jp/jis0208_index.js': {},
  'legacy-mb-japanese/euc-jp/jis0212_index.js': {},
  'legacy-mb-japanese/iso-2022-jp/iso2022jp-decoder.js': {},
  'legacy-mb-japanese/iso-2022-jp/iso2022jp-encoder.js': {
    before: (): void => {
      loadWptResource('./jis0208_index.js');
    },
  },
  'legacy-mb-japanese/iso-2022-jp/jis0208_index.js': {},
  'legacy-mb-japanese/shift_jis/jis0208_index.js': {},
  'legacy-mb-japanese/shift_jis/sjis-decoder.js': {},
  'legacy-mb-japanese/shift_jis/sjis-encoder.js': {
    before: (): void => {
      loadWptResource('./jis0208_index.js');
    },
  },
  'legacy-mb-korean/euc-kr/euckr-decoder.js': {},
  'legacy-mb-korean/euc-kr/euckr-encoder.js': {
    before: (): void => {
      loadWptResource('./euckr_index.js');
    },
  },
  'legacy-mb-korean/euc-kr/euckr_index.js': {},
  'legacy-mb-schinese/gb18030/gb18030-decoder.any.js': {},
  'legacy-mb-schinese/gbk/gbk-decoder.any.js': {},
  'legacy-mb-tchinese/big5/big5-decoder.js': {},
  'legacy-mb-tchinese/big5/big5-encoder.js': {
    before: (): void => {
      loadWptResource('./big5_index.js');
    },
  },
  'legacy-mb-tchinese/big5/big5_index.js': {},
  'replacement-encodings.any.js': {
    comment: 'XMLHttpRequest is not defined',
    expectedFailures: [
      'csiso2022kr - non-empty input decodes to one replacement character.',
      'csiso2022kr - empty input decodes to empty output.',
      'hz-gb-2312 - non-empty input decodes to one replacement character.',
      'hz-gb-2312 - empty input decodes to empty output.',
      'iso-2022-cn - non-empty input decodes to one replacement character.',
      'iso-2022-cn - empty input decodes to empty output.',
      'iso-2022-cn-ext - non-empty input decodes to one replacement character.',
      'iso-2022-cn-ext - empty input decodes to empty output.',
      'iso-2022-kr - non-empty input decodes to one replacement character.',
      'iso-2022-kr - empty input decodes to empty output.',
      'replacement - non-empty input decodes to one replacement character.',
      'replacement - empty input decodes to empty output.',
    ],
  },
  'single-byte-decoder.window.js': {
    comment: 'TODO(soon): Investigate these',
    expectedFailures: [
      'IBM866: 866 (XMLHttpRequest)',
      'IBM866: 866 (document.characterSet and document.inputEncoding)',
      'IBM866: cp866 (XMLHttpRequest)',
      'IBM866: cp866 (document.characterSet and document.inputEncoding)',
      'IBM866: csibm866 (XMLHttpRequest)',
      'IBM866: csibm866 (document.characterSet and document.inputEncoding)',
      'IBM866: ibm866 (XMLHttpRequest)',
      'IBM866: ibm866 (document.characterSet and document.inputEncoding)',
      'ISO-8859-2: csisolatin2 (XMLHttpRequest)',
      'ISO-8859-2: csisolatin2 (document.characterSet and document.inputEncoding)',
      'ISO-8859-2: iso-8859-2 (XMLHttpRequest)',
      'ISO-8859-2: iso-8859-2 (document.characterSet and document.inputEncoding)',
      'ISO-8859-2: iso-ir-101 (XMLHttpRequest)',
      'ISO-8859-2: iso-ir-101 (document.characterSet and document.inputEncoding)',
      'ISO-8859-2: iso8859-2 (XMLHttpRequest)',
      'ISO-8859-2: iso8859-2 (document.characterSet and document.inputEncoding)',
      'ISO-8859-2: iso88592 (XMLHttpRequest)',
      'ISO-8859-2: iso88592 (document.characterSet and document.inputEncoding)',
      'ISO-8859-2: iso_8859-2 (XMLHttpRequest)',
      'ISO-8859-2: iso_8859-2 (document.characterSet and document.inputEncoding)',
      'ISO-8859-2: iso_8859-2:1987 (XMLHttpRequest)',
      'ISO-8859-2: iso_8859-2:1987 (document.characterSet and document.inputEncoding)',
      'ISO-8859-2: l2 (XMLHttpRequest)',
      'ISO-8859-2: l2 (document.characterSet and document.inputEncoding)',
      'ISO-8859-2: latin2 (XMLHttpRequest)',
      'ISO-8859-2: latin2 (document.characterSet and document.inputEncoding)',
      'ISO-8859-3: csisolatin3 (XMLHttpRequest)',
      'ISO-8859-3: csisolatin3 (document.characterSet and document.inputEncoding)',
      'ISO-8859-3: iso-8859-3 (XMLHttpRequest)',
      'ISO-8859-3: iso-8859-3 (document.characterSet and document.inputEncoding)',
      'ISO-8859-3: iso-ir-109 (XMLHttpRequest)',
      'ISO-8859-3: iso-ir-109 (document.characterSet and document.inputEncoding)',
      'ISO-8859-3: iso8859-3 (XMLHttpRequest)',
      'ISO-8859-3: iso8859-3 (document.characterSet and document.inputEncoding)',
      'ISO-8859-3: iso88593 (XMLHttpRequest)',
      'ISO-8859-3: iso88593 (document.characterSet and document.inputEncoding)',
      'ISO-8859-3: iso_8859-3 (XMLHttpRequest)',
      'ISO-8859-3: iso_8859-3 (document.characterSet and document.inputEncoding)',
      'ISO-8859-3: iso_8859-3:1988 (XMLHttpRequest)',
      'ISO-8859-3: iso_8859-3:1988 (document.characterSet and document.inputEncoding)',
      'ISO-8859-3: l3 (XMLHttpRequest)',
      'ISO-8859-3: l3 (document.characterSet and document.inputEncoding)',
      'ISO-8859-3: latin3 (XMLHttpRequest)',
      'ISO-8859-3: latin3 (document.characterSet and document.inputEncoding)',
      'ISO-8859-4: csisolatin4 (XMLHttpRequest)',
      'ISO-8859-4: csisolatin4 (document.characterSet and document.inputEncoding)',
      'ISO-8859-4: iso-8859-4 (XMLHttpRequest)',
      'ISO-8859-4: iso-8859-4 (document.characterSet and document.inputEncoding)',
      'ISO-8859-4: iso-ir-110 (XMLHttpRequest)',
      'ISO-8859-4: iso-ir-110 (document.characterSet and document.inputEncoding)',
      'ISO-8859-4: iso8859-4 (XMLHttpRequest)',
      'ISO-8859-4: iso8859-4 (document.characterSet and document.inputEncoding)',
      'ISO-8859-4: iso88594 (XMLHttpRequest)',
      'ISO-8859-4: iso88594 (document.characterSet and document.inputEncoding)',
      'ISO-8859-4: iso_8859-4 (XMLHttpRequest)',
      'ISO-8859-4: iso_8859-4 (document.characterSet and document.inputEncoding)',
      'ISO-8859-4: iso_8859-4:1988 (XMLHttpRequest)',
      'ISO-8859-4: iso_8859-4:1988 (document.characterSet and document.inputEncoding)',
      'ISO-8859-4: l4 (XMLHttpRequest)',
      'ISO-8859-4: l4 (document.characterSet and document.inputEncoding)',
      'ISO-8859-4: latin4 (XMLHttpRequest)',
      'ISO-8859-4: latin4 (document.characterSet and document.inputEncoding)',
      'ISO-8859-5: csisolatincyrillic (XMLHttpRequest)',
      'ISO-8859-5: csisolatincyrillic (document.characterSet and document.inputEncoding)',
      'ISO-8859-5: cyrillic (XMLHttpRequest)',
      'ISO-8859-5: cyrillic (document.characterSet and document.inputEncoding)',
      'ISO-8859-5: iso-8859-5 (XMLHttpRequest)',
      'ISO-8859-5: iso-8859-5 (document.characterSet and document.inputEncoding)',
      'ISO-8859-5: iso-ir-144 (XMLHttpRequest)',
      'ISO-8859-5: iso-ir-144 (document.characterSet and document.inputEncoding)',
      'ISO-8859-5: iso8859-5 (XMLHttpRequest)',
      'ISO-8859-5: iso8859-5 (document.characterSet and document.inputEncoding)',
      'ISO-8859-5: iso88595 (XMLHttpRequest)',
      'ISO-8859-5: iso88595 (document.characterSet and document.inputEncoding)',
      'ISO-8859-5: iso_8859-5 (XMLHttpRequest)',
      'ISO-8859-5: iso_8859-5 (document.characterSet and document.inputEncoding)',
      'ISO-8859-5: iso_8859-5:1988 (XMLHttpRequest)',
      'ISO-8859-5: iso_8859-5:1988 (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: arabic (XMLHttpRequest)',
      'ISO-8859-6: arabic (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: asmo-708 (XMLHttpRequest)',
      'ISO-8859-6: asmo-708 (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: csiso88596e (XMLHttpRequest)',
      'ISO-8859-6: csiso88596e (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: csiso88596i (XMLHttpRequest)',
      'ISO-8859-6: csiso88596i (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: csisolatinarabic (XMLHttpRequest)',
      'ISO-8859-6: csisolatinarabic (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: ecma-114 (XMLHttpRequest)',
      'ISO-8859-6: ecma-114 (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: iso-8859-6 (XMLHttpRequest)',
      'ISO-8859-6: iso-8859-6 (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: iso-8859-6-e (XMLHttpRequest)',
      'ISO-8859-6: iso-8859-6-e (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: iso-8859-6-i (XMLHttpRequest)',
      'ISO-8859-6: iso-8859-6-i (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: iso-ir-127 (XMLHttpRequest)',
      'ISO-8859-6: iso-ir-127 (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: iso8859-6 (XMLHttpRequest)',
      'ISO-8859-6: iso8859-6 (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: iso88596 (XMLHttpRequest)',
      'ISO-8859-6: iso88596 (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: iso_8859-6 (XMLHttpRequest)',
      'ISO-8859-6: iso_8859-6 (document.characterSet and document.inputEncoding)',
      'ISO-8859-6: iso_8859-6:1987 (XMLHttpRequest)',
      'ISO-8859-6: iso_8859-6:1987 (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: csisolatingreek (XMLHttpRequest)',
      'ISO-8859-7: csisolatingreek (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: ecma-118 (XMLHttpRequest)',
      'ISO-8859-7: ecma-118 (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: elot_928 (XMLHttpRequest)',
      'ISO-8859-7: elot_928 (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: greek (XMLHttpRequest)',
      'ISO-8859-7: greek (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: greek8 (XMLHttpRequest)',
      'ISO-8859-7: greek8 (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: iso-8859-7 (XMLHttpRequest)',
      'ISO-8859-7: iso-8859-7 (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: iso-ir-126 (XMLHttpRequest)',
      'ISO-8859-7: iso-ir-126 (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: iso8859-7 (XMLHttpRequest)',
      'ISO-8859-7: iso8859-7 (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: iso88597 (XMLHttpRequest)',
      'ISO-8859-7: iso88597 (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: iso_8859-7 (XMLHttpRequest)',
      'ISO-8859-7: iso_8859-7 (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: iso_8859-7:1987 (XMLHttpRequest)',
      'ISO-8859-7: iso_8859-7:1987 (document.characterSet and document.inputEncoding)',
      'ISO-8859-7: sun_eu_greek (XMLHttpRequest)',
      'ISO-8859-7: sun_eu_greek (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: csiso88598e (XMLHttpRequest)',
      'ISO-8859-8: csiso88598e (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: csisolatinhebrew (XMLHttpRequest)',
      'ISO-8859-8: csisolatinhebrew (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: hebrew (XMLHttpRequest)',
      'ISO-8859-8: hebrew (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: iso-8859-8 (XMLHttpRequest)',
      'ISO-8859-8: iso-8859-8 (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: iso-8859-8-e (XMLHttpRequest)',
      'ISO-8859-8: iso-8859-8-e (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: iso-ir-138 (XMLHttpRequest)',
      'ISO-8859-8: iso-ir-138 (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: iso8859-8 (XMLHttpRequest)',
      'ISO-8859-8: iso8859-8 (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: iso88598 (XMLHttpRequest)',
      'ISO-8859-8: iso88598 (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: iso_8859-8 (XMLHttpRequest)',
      'ISO-8859-8: iso_8859-8 (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: iso_8859-8:1988 (XMLHttpRequest)',
      'ISO-8859-8: iso_8859-8:1988 (document.characterSet and document.inputEncoding)',
      'ISO-8859-8: visual (XMLHttpRequest)',
      'ISO-8859-8: visual (document.characterSet and document.inputEncoding)',
      'ISO-8859-8-I: csiso88598i (XMLHttpRequest)',
      'ISO-8859-8-I: csiso88598i (document.characterSet and document.inputEncoding)',
      'ISO-8859-8-I: iso-8859-8-i (XMLHttpRequest)',
      'ISO-8859-8-I: iso-8859-8-i (document.characterSet and document.inputEncoding)',
      'ISO-8859-8-I: logical (XMLHttpRequest)',
      'ISO-8859-8-I: logical (document.characterSet and document.inputEncoding)',
      'ISO-8859-10: csisolatin6 (XMLHttpRequest)',
      'ISO-8859-10: csisolatin6 (document.characterSet and document.inputEncoding)',
      'ISO-8859-10: iso-8859-10 (XMLHttpRequest)',
      'ISO-8859-10: iso-8859-10 (document.characterSet and document.inputEncoding)',
      'ISO-8859-10: iso-ir-157 (XMLHttpRequest)',
      'ISO-8859-10: iso-ir-157 (document.characterSet and document.inputEncoding)',
      'ISO-8859-10: iso8859-10 (XMLHttpRequest)',
      'ISO-8859-10: iso8859-10 (document.characterSet and document.inputEncoding)',
      'ISO-8859-10: iso885910 (XMLHttpRequest)',
      'ISO-8859-10: iso885910 (document.characterSet and document.inputEncoding)',
      'ISO-8859-10: l6 (XMLHttpRequest)',
      'ISO-8859-10: l6 (document.characterSet and document.inputEncoding)',
      'ISO-8859-10: latin6 (XMLHttpRequest)',
      'ISO-8859-10: latin6 (document.characterSet and document.inputEncoding)',
      'ISO-8859-13: iso-8859-13 (XMLHttpRequest)',
      'ISO-8859-13: iso-8859-13 (document.characterSet and document.inputEncoding)',
      'ISO-8859-13: iso8859-13 (XMLHttpRequest)',
      'ISO-8859-13: iso8859-13 (document.characterSet and document.inputEncoding)',
      'ISO-8859-13: iso885913 (XMLHttpRequest)',
      'ISO-8859-13: iso885913 (document.characterSet and document.inputEncoding)',
      'ISO-8859-14: iso-8859-14 (XMLHttpRequest)',
      'ISO-8859-14: iso-8859-14 (document.characterSet and document.inputEncoding)',
      'ISO-8859-14: iso8859-14 (XMLHttpRequest)',
      'ISO-8859-14: iso8859-14 (document.characterSet and document.inputEncoding)',
      'ISO-8859-14: iso885914 (XMLHttpRequest)',
      'ISO-8859-14: iso885914 (document.characterSet and document.inputEncoding)',
      'ISO-8859-15: csisolatin9 (XMLHttpRequest)',
      'ISO-8859-15: csisolatin9 (document.characterSet and document.inputEncoding)',
      'ISO-8859-15: iso-8859-15 (XMLHttpRequest)',
      'ISO-8859-15: iso-8859-15 (document.characterSet and document.inputEncoding)',
      'ISO-8859-15: iso8859-15 (XMLHttpRequest)',
      'ISO-8859-15: iso8859-15 (document.characterSet and document.inputEncoding)',
      'ISO-8859-15: iso885915 (XMLHttpRequest)',
      'ISO-8859-15: iso885915 (document.characterSet and document.inputEncoding)',
      'ISO-8859-15: iso_8859-15 (XMLHttpRequest)',
      'ISO-8859-15: iso_8859-15 (document.characterSet and document.inputEncoding)',
      'ISO-8859-15: l9 (XMLHttpRequest)',
      'ISO-8859-15: l9 (document.characterSet and document.inputEncoding)',
      'ISO-8859-16: iso-8859-16 (XMLHttpRequest)',
      'ISO-8859-16: iso-8859-16 (document.characterSet and document.inputEncoding)',
      'KOI8-R: cskoi8r (XMLHttpRequest)',
      'KOI8-R: cskoi8r (document.characterSet and document.inputEncoding)',
      'KOI8-R: koi (XMLHttpRequest)',
      'KOI8-R: koi (document.characterSet and document.inputEncoding)',
      'KOI8-R: koi8 (XMLHttpRequest)',
      'KOI8-R: koi8 (document.characterSet and document.inputEncoding)',
      'KOI8-R: koi8-r (XMLHttpRequest)',
      'KOI8-R: koi8-r (document.characterSet and document.inputEncoding)',
      'KOI8-R: koi8_r (XMLHttpRequest)',
      'KOI8-R: koi8_r (document.characterSet and document.inputEncoding)',
      'KOI8-U: koi8-ru (XMLHttpRequest)',
      'KOI8-U: koi8-ru (document.characterSet and document.inputEncoding)',
      'KOI8-U: koi8-u (XMLHttpRequest)',
      'KOI8-U: koi8-u (document.characterSet and document.inputEncoding)',
      'macintosh: csmacintosh (XMLHttpRequest)',
      'macintosh: csmacintosh (document.characterSet and document.inputEncoding)',
      'macintosh: mac (XMLHttpRequest)',
      'macintosh: mac (document.characterSet and document.inputEncoding)',
      'macintosh: macintosh (XMLHttpRequest)',
      'macintosh: macintosh (document.characterSet and document.inputEncoding)',
      'macintosh: x-mac-roman (XMLHttpRequest)',
      'macintosh: x-mac-roman (document.characterSet and document.inputEncoding)',
      'windows-874: dos-874 (XMLHttpRequest)',
      'windows-874: dos-874 (document.characterSet and document.inputEncoding)',
      'windows-874: iso-8859-11 (XMLHttpRequest)',
      'windows-874: iso-8859-11 (document.characterSet and document.inputEncoding)',
      'windows-874: iso8859-11 (XMLHttpRequest)',
      'windows-874: iso8859-11 (document.characterSet and document.inputEncoding)',
      'windows-874: iso885911 (XMLHttpRequest)',
      'windows-874: iso885911 (document.characterSet and document.inputEncoding)',
      'windows-874: tis-620 (XMLHttpRequest)',
      'windows-874: tis-620 (document.characterSet and document.inputEncoding)',
      'windows-874: windows-874 (XMLHttpRequest)',
      'windows-874: windows-874 (document.characterSet and document.inputEncoding)',
      'windows-1250: cp1250 (XMLHttpRequest)',
      'windows-1250: cp1250 (document.characterSet and document.inputEncoding)',
      'windows-1250: windows-1250 (XMLHttpRequest)',
      'windows-1250: windows-1250 (document.characterSet and document.inputEncoding)',
      'windows-1250: x-cp1250 (XMLHttpRequest)',
      'windows-1250: x-cp1250 (document.characterSet and document.inputEncoding)',
      'windows-1251: cp1251 (XMLHttpRequest)',
      'windows-1251: cp1251 (document.characterSet and document.inputEncoding)',
      'windows-1251: windows-1251 (XMLHttpRequest)',
      'windows-1251: windows-1251 (document.characterSet and document.inputEncoding)',
      'windows-1251: x-cp1251 (XMLHttpRequest)',
      'windows-1251: x-cp1251 (document.characterSet and document.inputEncoding)',
      'windows-1252: ansi_x3.4-1968 (XMLHttpRequest)',
      'windows-1252: ansi_x3.4-1968 (document.characterSet and document.inputEncoding)',
      'windows-1252: ascii (XMLHttpRequest)',
      'windows-1252: ascii (document.characterSet and document.inputEncoding)',
      'windows-1252: cp1252 (XMLHttpRequest)',
      'windows-1252: cp1252 (document.characterSet and document.inputEncoding)',
      'windows-1252: cp819 (XMLHttpRequest)',
      'windows-1252: cp819 (document.characterSet and document.inputEncoding)',
      'windows-1252: csisolatin1 (XMLHttpRequest)',
      'windows-1252: csisolatin1 (document.characterSet and document.inputEncoding)',
      'windows-1252: ibm819 (XMLHttpRequest)',
      'windows-1252: ibm819 (document.characterSet and document.inputEncoding)',
      'windows-1252: iso-8859-1 (XMLHttpRequest)',
      'windows-1252: iso-8859-1 (document.characterSet and document.inputEncoding)',
      'windows-1252: iso-ir-100 (XMLHttpRequest)',
      'windows-1252: iso-ir-100 (document.characterSet and document.inputEncoding)',
      'windows-1252: iso8859-1 (XMLHttpRequest)',
      'windows-1252: iso8859-1 (document.characterSet and document.inputEncoding)',
      'windows-1252: iso88591 (XMLHttpRequest)',
      'windows-1252: iso88591 (document.characterSet and document.inputEncoding)',
      'windows-1252: iso_8859-1 (XMLHttpRequest)',
      'windows-1252: iso_8859-1 (document.characterSet and document.inputEncoding)',
      'windows-1252: iso_8859-1:1987 (XMLHttpRequest)',
      'windows-1252: iso_8859-1:1987 (document.characterSet and document.inputEncoding)',
      'windows-1252: l1 (XMLHttpRequest)',
      'windows-1252: l1 (document.characterSet and document.inputEncoding)',
      'windows-1252: latin1 (XMLHttpRequest)',
      'windows-1252: latin1 (document.characterSet and document.inputEncoding)',
      'windows-1252: us-ascii (XMLHttpRequest)',
      'windows-1252: us-ascii (document.characterSet and document.inputEncoding)',
      'windows-1252: windows-1252 (XMLHttpRequest)',
      'windows-1252: windows-1252 (document.characterSet and document.inputEncoding)',
      'windows-1252: x-cp1252 (XMLHttpRequest)',
      'windows-1252: x-cp1252 (document.characterSet and document.inputEncoding)',
      'windows-1253: cp1253 (XMLHttpRequest)',
      'windows-1253: cp1253 (document.characterSet and document.inputEncoding)',
      'windows-1253: windows-1253 (XMLHttpRequest)',
      'windows-1253: windows-1253 (document.characterSet and document.inputEncoding)',
      'windows-1253: x-cp1253 (XMLHttpRequest)',
      'windows-1253: x-cp1253 (document.characterSet and document.inputEncoding)',
      'windows-1254: cp1254 (XMLHttpRequest)',
      'windows-1254: cp1254 (document.characterSet and document.inputEncoding)',
      'windows-1254: csisolatin5 (XMLHttpRequest)',
      'windows-1254: csisolatin5 (document.characterSet and document.inputEncoding)',
      'windows-1254: iso-8859-9 (XMLHttpRequest)',
      'windows-1254: iso-8859-9 (document.characterSet and document.inputEncoding)',
      'windows-1254: iso-ir-148 (XMLHttpRequest)',
      'windows-1254: iso-ir-148 (document.characterSet and document.inputEncoding)',
      'windows-1254: iso8859-9 (XMLHttpRequest)',
      'windows-1254: iso8859-9 (document.characterSet and document.inputEncoding)',
      'windows-1254: iso88599 (XMLHttpRequest)',
      'windows-1254: iso88599 (document.characterSet and document.inputEncoding)',
      'windows-1254: iso_8859-9 (XMLHttpRequest)',
      'windows-1254: iso_8859-9 (document.characterSet and document.inputEncoding)',
      'windows-1254: iso_8859-9:1989 (XMLHttpRequest)',
      'windows-1254: iso_8859-9:1989 (document.characterSet and document.inputEncoding)',
      'windows-1254: l5 (XMLHttpRequest)',
      'windows-1254: l5 (document.characterSet and document.inputEncoding)',
      'windows-1254: latin5 (XMLHttpRequest)',
      'windows-1254: latin5 (document.characterSet and document.inputEncoding)',
      'windows-1254: windows-1254 (XMLHttpRequest)',
      'windows-1254: windows-1254 (document.characterSet and document.inputEncoding)',
      'windows-1254: x-cp1254 (XMLHttpRequest)',
      'windows-1254: x-cp1254 (document.characterSet and document.inputEncoding)',
      'windows-1255: cp1255 (XMLHttpRequest)',
      'windows-1255: cp1255 (document.characterSet and document.inputEncoding)',
      'windows-1255: windows-1255 (XMLHttpRequest)',
      'windows-1255: windows-1255 (document.characterSet and document.inputEncoding)',
      'windows-1255: x-cp1255 (XMLHttpRequest)',
      'windows-1255: x-cp1255 (document.characterSet and document.inputEncoding)',
      'windows-1256: cp1256 (XMLHttpRequest)',
      'windows-1256: cp1256 (document.characterSet and document.inputEncoding)',
      'windows-1256: windows-1256 (XMLHttpRequest)',
      'windows-1256: windows-1256 (document.characterSet and document.inputEncoding)',
      'windows-1256: x-cp1256 (XMLHttpRequest)',
      'windows-1256: x-cp1256 (document.characterSet and document.inputEncoding)',
      'windows-1257: cp1257 (XMLHttpRequest)',
      'windows-1257: cp1257 (document.characterSet and document.inputEncoding)',
      'windows-1257: windows-1257 (XMLHttpRequest)',
      'windows-1257: windows-1257 (document.characterSet and document.inputEncoding)',
      'windows-1257: x-cp1257 (XMLHttpRequest)',
      'windows-1257: x-cp1257 (document.characterSet and document.inputEncoding)',
      'windows-1258: cp1258 (XMLHttpRequest)',
      'windows-1258: cp1258 (document.characterSet and document.inputEncoding)',
      'windows-1258: windows-1258 (XMLHttpRequest)',
      'windows-1258: windows-1258 (document.characterSet and document.inputEncoding)',
      'windows-1258: x-cp1258 (XMLHttpRequest)',
      'windows-1258: x-cp1258 (document.characterSet and document.inputEncoding)',
      'x-mac-cyrillic: x-mac-cyrillic (XMLHttpRequest)',
      'x-mac-cyrillic: x-mac-cyrillic (document.characterSet and document.inputEncoding)',
      'x-mac-cyrillic: x-mac-ukrainian (XMLHttpRequest)',
      'x-mac-cyrillic: x-mac-ukrainian (document.characterSet and document.inputEncoding)',
    ],
  },
  'streams/backpressure.any.js': {
    comment: 'Implement step_timeout in harness',
    expectedFailures: [
      'write() should not complete until read relieves backpressure for TextDecoderStream',
      'additional writes should wait for backpressure to be relieved for class TextDecoderStream',
      'write() should not complete until read relieves backpressure for TextEncoderStream',
      'additional writes should wait for backpressure to be relieved for class TextEncoderStream',
    ],
  },
  'streams/decode-attributes.any.js': {},
  'streams/decode-bad-chunks.any.js': {},
  'streams/decode-ignore-bom.any.js': {},
  'streams/decode-incomplete-input.any.js': {},
  'streams/decode-non-utf8.any.js': {},
  'streams/decode-split-character.any.js': {},
  'streams/decode-utf8.any.js': {
    comment: 'Enable once MessageChannel is implemented',
    expectedFailures: [
      'decoding a transferred Uint8Array chunk should give no output',
      'decoding a transferred ArrayBuffer chunk should give no output',
    ],
  },
  'streams/encode-bad-chunks.any.js': {},
  'streams/encode-utf8.any.js': {},
  'streams/invalid-realm.window.js': {
    comment: 'Enable when ShadowRealm is supported',
    expectedFailures: [
      'TextDecoderStream: write in detached realm should succeed',
      'TextEncoderStream: write in detached realm should succeed',
      'TextEncoderStream: close in detached realm should succeed',
      'TextDecoderStream: close in detached realm should succeed',
    ],
  },
  'streams/readable-writable-properties.any.js': {},
  'streams/realms.window.js': {
    comment: 'ReferenceError: window is not defined',
    omittedTests: true,
  },
  'textdecoder-arguments.any.js': {},
  'textdecoder-byte-order-marks.any.js': {},
  'textdecoder-copy.any.js': {},
  'textdecoder-eof.any.js': {},
  'textdecoder-fatal-single-byte.any.js': {},
  'textdecoder-fatal-streaming.any.js': {},
  'textdecoder-fatal.any.js': {},
  'textdecoder-ignorebom.any.js': {},
  'textdecoder-labels.any.js': {},
  'textdecoder-streaming.any.js': {},
  'textdecoder-utf16-surrogates.any.js': {},
  'textencoder-constructor-non-utf.any.js': {},
  'textencoder-utf16-surrogates.any.js': {},
  'unsupported-encodings.any.js': {
    comment: 'XMLHttpRequest is not defined',
    expectedFailures: [
      'UTF-7 should not be supported',
      'utf-7 should not be supported',
      'UTF-32 with BOM should decode as UTF-16LE',
      'UTF-32 with no BOM should decode as UTF-8',
      'utf-32 with BOM should decode as UTF-16LE',
      'utf-32 with no BOM should decode as UTF-8',
      'UTF-32LE with BOM should decode as UTF-16LE',
      'UTF-32LE with no BOM should decode as UTF-8',
      'utf-32le with BOM should decode as UTF-16LE',
      'utf-32le with no BOM should decode as UTF-8',
      'UTF-32be with no BOM should decode as UTF-8',
      'UTF-32be with BOM should decode as UTF-8',
      'utf-32be with no BOM should decode as UTF-8',
      'utf-32be with BOM should decode as UTF-8',
    ],
  },
  'unsupported-labels.window.js': {
    comment: 'Too many failures to list by name',
    expectedFailures: [
      '437 is not supported by the Encoding Standard',
      'adobe-standard-encoding is not supported by the Encoding Standard',
      'armscii-8 is not supported by the Encoding Standard',
      'bocu-1 is not supported by the Encoding Standard',
      'cesu-8 is not supported by the Encoding Standard',
      'cp1025 is not supported by the Encoding Standard',
      'cp437 is not supported by the Encoding Standard',
      'cp737 is not supported by the Encoding Standard',
      'cp851 is not supported by the Encoding Standard',
      'cp858 is not supported by the Encoding Standard',
      'cp862 is not supported by the Encoding Standard',
      'cp864 is not supported by the Encoding Standard',
      'cp869 is not supported by the Encoding Standard',
      'cp875 is not supported by the Encoding Standard',
      'cp950 is not supported by the Encoding Standard',
      'csiso103t618bit is not supported by the Encoding Standard',
      'csiso111ecmacyrillic is not supported by the Encoding Standard',
      'cspc8codepage437 is not supported by the Encoding Standard',
      'csviscii is not supported by the Encoding Standard',
      'dos-720 is not supported by the Encoding Standard',
      'dos-862 is not supported by the Encoding Standard',
      'ecma-cyrillic is not supported by the Encoding Standard',
      'euc-tw is not supported by the Encoding Standard',
      'german is not supported by the Encoding Standard',
      'geostd8 is not supported by the Encoding Standard',
      'hp-roman8 is not supported by the Encoding Standard',
      'ibm-thai is not supported by the Encoding Standard',
      'ibm00858 is not supported by the Encoding Standard',
      'ibm00924 is not supported by the Encoding Standard',
      'ibm01047 is not supported by the Encoding Standard',
      'ibm01140 is not supported by the Encoding Standard',
      'ibm01141 is not supported by the Encoding Standard',
      'ibm01142 is not supported by the Encoding Standard',
      'ibm01143 is not supported by the Encoding Standard',
      'ibm01144 is not supported by the Encoding Standard',
      'ibm01145 is not supported by the Encoding Standard',
      'ibm01146 is not supported by the Encoding Standard',
      'ibm01147 is not supported by the Encoding Standard',
      'ibm01148 is not supported by the Encoding Standard',
      'ibm01149 is not supported by the Encoding Standard',
      'ibm037 is not supported by the Encoding Standard',
      'ibm1026 is not supported by the Encoding Standard',
      'ibm1047 is not supported by the Encoding Standard',
      'ibm273 is not supported by the Encoding Standard',
      'ibm277 is not supported by the Encoding Standard',
      'ibm278 is not supported by the Encoding Standard',
      'ibm280 is not supported by the Encoding Standard',
      'ibm284 is not supported by the Encoding Standard',
      'ibm285 is not supported by the Encoding Standard',
      'ibm290 is not supported by the Encoding Standard',
      'ibm297 is not supported by the Encoding Standard',
      'ibm367 is not supported by the Encoding Standard',
      'ibm420 is not supported by the Encoding Standard',
      'ibm423 is not supported by the Encoding Standard',
      'ibm424 is not supported by the Encoding Standard',
      'ibm437 is not supported by the Encoding Standard',
      'ibm500 is not supported by the Encoding Standard',
      'ibm737 is not supported by the Encoding Standard',
      'ibm775 is not supported by the Encoding Standard',
      'ibm850 is not supported by the Encoding Standard',
      'ibm852 is not supported by the Encoding Standard',
      'ibm855 is not supported by the Encoding Standard',
      'ibm857 is not supported by the Encoding Standard',
      'ibm860 is not supported by the Encoding Standard',
      'ibm861 is not supported by the Encoding Standard',
      'ibm862 is not supported by the Encoding Standard',
      'ibm863 is not supported by the Encoding Standard',
      'ibm864 is not supported by the Encoding Standard',
      'ibm864i is not supported by the Encoding Standard',
      'ibm865 is not supported by the Encoding Standard',
      'ibm868 is not supported by the Encoding Standard',
      'ibm869 is not supported by the Encoding Standard',
      'ibm870 is not supported by the Encoding Standard',
      'ibm871 is not supported by the Encoding Standard',
      'ibm880 is not supported by the Encoding Standard',
      'ibm905 is not supported by the Encoding Standard',
      'ibm918 is not supported by the Encoding Standard',
      'iso-2022-jp-1 is not supported by the Encoding Standard',
      'iso-2022-jp-2 is not supported by the Encoding Standard',
      'iso-2022-jp-3 is not supported by the Encoding Standard',
      'iso-8859-8 visual is not supported by the Encoding Standard',
      'jis_c6226-1978 is not supported by the Encoding Standard',
      'jis_x0208-1983 is not supported by the Encoding Standard',
      'jis_x0208-1990 is not supported by the Encoding Standard',
      'jis_x0212-1990 is not supported by the Encoding Standard',
      'johab is not supported by the Encoding Standard',
      'latin9 is not supported by the Encoding Standard',
      'norwegian is not supported by the Encoding Standard',
      'sami-ws2 is not supported by the Encoding Standard',
      'scsu is not supported by the Encoding Standard',
      'shift_jis_x0213-2000 is not supported by the Encoding Standard',
      'swedish is not supported by the Encoding Standard',
      'tcvn is not supported by the Encoding Standard',
      'tis-620-2533 is not supported by the Encoding Standard',
      'utf-7 is not supported by the Encoding Standard',
      'utf-32 is not supported by the Encoding Standard',
      'viscii is not supported by the Encoding Standard',
      'windows-936-2000 is not supported by the Encoding Standard',
      'windows-sami-2 is not supported by the Encoding Standard',
      'ws2 is not supported by the Encoding Standard',
      'x-chinese-cns is not supported by the Encoding Standard',
      'x-chinese-eten is not supported by the Encoding Standard',
      'x-cp20001 is not supported by the Encoding Standard',
      'x-cp20003 is not supported by the Encoding Standard',
      'x-cp20004 is not supported by the Encoding Standard',
      'x-cp20005 is not supported by the Encoding Standard',
      'x-cp20261 is not supported by the Encoding Standard',
      'x-cp20269 is not supported by the Encoding Standard',
      'x-cp20936 is not supported by the Encoding Standard',
      'x-cp20949 is not supported by the Encoding Standard',
      'x-cp21027 is not supported by the Encoding Standard',
      'x-cp50227 is not supported by the Encoding Standard',
      'x-cp50229 is not supported by the Encoding Standard',
      'x-ebcdic-koreanextended is not supported by the Encoding Standard',
      'x-europa is not supported by the Encoding Standard',
      'x-ia5 is not supported by the Encoding Standard',
      'x-ia5-german is not supported by the Encoding Standard',
      'x-ia5-norwegian is not supported by the Encoding Standard',
      'x-ia5-swedish is not supported by the Encoding Standard',
      'x-iscii-as is not supported by the Encoding Standard',
      'x-iscii-be is not supported by the Encoding Standard',
      'x-iscii-de is not supported by the Encoding Standard',
      'x-iscii-gu is not supported by the Encoding Standard',
      'x-iscii-ka is not supported by the Encoding Standard',
      'x-iscii-ma is not supported by the Encoding Standard',
      'x-iscii-or is not supported by the Encoding Standard',
      'x-iscii-pa is not supported by the Encoding Standard',
      'x-iscii-t is not supported by the Encoding Standard',
      'x-iscii-ta is not supported by the Encoding Standard',
      'x-iscii-te is not supported by the Encoding Standard',
      'x-mac-arabic is not supported by the Encoding Standard',
      'x-mac-ce is not supported by the Encoding Standard',
      'x-mac-centraleurroman is not supported by the Encoding Standard',
      'x-mac-chinesesimp is not supported by the Encoding Standard',
      'x-mac-chinesetrad is not supported by the Encoding Standard',
      'x-mac-croatian is not supported by the Encoding Standard',
      'x-mac-devanagari is not supported by the Encoding Standard',
      'x-mac-dingbats is not supported by the Encoding Standard',
      'x-mac-farsi is not supported by the Encoding Standard',
      'x-mac-greek is not supported by the Encoding Standard',
      'x-mac-gujarati is not supported by the Encoding Standard',
      'x-mac-gurmukhi is not supported by the Encoding Standard',
      'x-mac-hebrew is not supported by the Encoding Standard',
      'x-mac-icelandic is not supported by the Encoding Standard',
      'x-mac-japanese is not supported by the Encoding Standard',
      'x-mac-korean is not supported by the Encoding Standard',
      'x-mac-roman-latin1 is not supported by the Encoding Standard',
      'x-mac-romanian is not supported by the Encoding Standard',
      'x-mac-symbol is not supported by the Encoding Standard',
      'x-mac-thai is not supported by the Encoding Standard',
      'x-mac-tibetan is not supported by the Encoding Standard',
      'x-mac-turkish is not supported by the Encoding Standard',
      'x-mac-vt100 is not supported by the Encoding Standard',
      'x-nextstep is not supported by the Encoding Standard',
      'x-vps is not supported by the Encoding Standard',
      '_autodetect is not supported by the Encoding Standard',
      '_autodetect_all is not supported by the Encoding Standard',
      '_autodetect_kr is not supported by the Encoding Standard',
    ],
  },
} satisfies TestRunnerConfig;
