// Copyright (c) 2017-2022 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0

import { type TestRunnerConfig } from 'harness/harness';

export default {
  'dedicated-worker/eventsource-close.js': {},
  'dedicated-worker/eventsource-close2.js': {},
  'dedicated-worker/eventsource-constructor-no-new.any.js': {},
  'dedicated-worker/eventsource-constructor-non-same-origin.js': {},
  'dedicated-worker/eventsource-constructor-url-bogus.js': {},
  'dedicated-worker/eventsource-eventtarget.worker.js': {},
  'dedicated-worker/eventsource-onmesage.js': {},
  'dedicated-worker/eventsource-onopen.js': {},
  'dedicated-worker/eventsource-prototype.js': {},
  'dedicated-worker/eventsource-url.js': {},
  'event-data.any.js': {},
  'eventsource-close.window.js': {},
  'eventsource-constructor-document-domain.window.js': {},
  'eventsource-constructor-empty-url.any.js': {},
  'eventsource-constructor-non-same-origin.window.js': {},
  'eventsource-constructor-stringify.window.js': {},
  'eventsource-constructor-url-bogus.any.js': {},
  'eventsource-cross-origin.window.js': {},
  'eventsource-eventtarget.any.js': {},
  'eventsource-onmessage-trusted.any.js': {},
  'eventsource-onmessage.any.js': {},
  'eventsource-onopen.any.js': {},
  'eventsource-prototype.any.js': {},
  'eventsource-reconnect.window.js': {},
  'eventsource-request-cancellation.window.js': {},
  'eventsource-url.any.js': {},
  'format-bom-2.any.js': {},
  'format-bom.any.js': {},
  'format-comments.any.js': {},
  'format-data-before-final-empty-line.any.js': {},
  'format-field-data.any.js': {},
  'format-field-event-empty.any.js': {},
  'format-field-event.any.js': {},
  'format-field-id-2.any.js': {},
  'format-field-id-3.window.js': {},
  'format-field-id-null.window.js': {},
  'format-field-id.any.js': {},
  'format-field-parsing.any.js': {},
  'format-field-retry-bogus.any.js': {},
  'format-field-retry-empty.any.js': {},
  'format-field-retry.any.js': {},
  'format-field-unknown.any.js': {},
  'format-leading-space.any.js': {},
  'format-mime-bogus.any.js': {},
  'format-mime-trailing-semicolon.any.js': {},
  'format-mime-valid-bogus.any.js': {},
  'format-newlines.any.js': {},
  'format-null-character.any.js': {},
  'format-utf-8.any.js': {},
  'request-accept.any.js': {},
  'request-cache-control.any.js': {
    comment: "Triggers an error in the backend server. KeyError: b'origin'",
    skipAllTests: true,
  },
  'request-credentials.window.js': {
    comment: 'ReferenceError: document is not defined',
    skipAllTests: true,
  },
  'request-redirect.window.js': {
    comment: 'ReferenceError: document is not defined',
    skipAllTests: true,
  },
  'request-status-error.window.js': {
    comment: 'ReferenceError: document is not defined',
    skipAllTests: true,
  },
  'shared-worker/eventsource-close.js': {},
  'shared-worker/eventsource-constructor-non-same-origin.js': {},
  'shared-worker/eventsource-constructor-url-bogus.js': {},
  'shared-worker/eventsource-eventtarget.js': {},
  'shared-worker/eventsource-onmesage.js': {},
  'shared-worker/eventsource-onopen.js': {},
  'shared-worker/eventsource-prototype.js': {},
  'shared-worker/eventsource-url.js': {},
} satisfies TestRunnerConfig;
