// Copyright (c) 2017-2026 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0

import { type TestRunnerConfig } from 'harness/harness';

export default {
  'ecmascript-binding/builtin-function-properties.any.js': {},
  'ecmascript-binding/class-string-interface.any.js': {
    comment: '@@toStringTag property descriptor mismatch',
    expectedFailures: [
      '@@toStringTag exists on the prototype with the appropriate descriptor',
    ],
  },
  'ecmascript-binding/class-string-iterator-prototype-object.any.js': {
    comment: 'Iterator @@toStringTag is different in workerd',
    expectedFailures: [
      '@@toStringTag exists with the appropriate descriptor',
      'Object.prototype.toString',
      'Object.prototype.toString applied to a null-prototype instance',
    ],
  },
  'ecmascript-binding/class-string-named-properties-object.window.js': {
    comment: 'Window-specific test',
    omittedTests: true,
  },
  'ecmascript-binding/es-exceptions/DOMException-constants.any.js': {
    comment: 'DOMException constants have wrong configurable descriptor',
    expectedFailures: true,
  },
  'ecmascript-binding/es-exceptions/DOMException-constructor-and-prototype.any.js':
    {
      comment: 'DOMException property descriptors differ from spec',
      expectedFailures: true,
    },
  'ecmascript-binding/es-exceptions/DOMException-constructor-behavior.any.js': {
    comment: 'DOMException property inheritance differs from spec',
    expectedFailures: true,
  },
  'ecmascript-binding/es-exceptions/DOMException-custom-bindings.any.js': {
    comment: 'DOMException property descriptors differ from spec',
    expectedFailures: true,
  },
  'ecmascript-binding/es-exceptions/DOMException-is-error.any.js': {
    comment: 'DOMException.prototype not in Error.prototype chain',
    expectedFailures: [''],
  },
  'ecmascript-binding/global-immutable-prototype.any.js': {
    comment: 'globalThis prototype is unconfigurable in workerd',
    expectedFailures: true,
  },
  'ecmascript-binding/global-mutable-prototype.any.js': {
    comment: 'globalThis prototype is unconfigurable in workerd',
    expectedFailures: true,
  },
  'ecmascript-binding/global-object-implicit-this-value.any.js': {
    comment:
      'Script fails to load - addEventListener is not defined in workerd',
    expectedFailures: [
      "Global object's getter throws when called on incompatible object",
      "Global object's setter throws when called on incompatible object",
      "Global object's operation throws when called on incompatible object",
      "Global object's getter works when called on null / undefined",
      "Global object's setter works when called on null / undefined",
      "Global object's operation works when called on null / undefined",
    ],
  },
  'ecmascript-binding/legacy-factor-function-subclass.window.js': {
    comment: 'Window-specific test',
    omittedTests: true,
  },
  'ecmascript-binding/legacy-factory-function-builtin-properties.window.js': {
    comment: 'Window-specific test',
    omittedTests: true,
  },
  'ecmascript-binding/legacy-platform-object/helper.js': {},
  'ecmascript-binding/no-regexp-special-casing.any.js': {
    comment: 'self.addEventListener is not available in workerd',
    expectedFailures: [
      'Conversion to a dictionary works',
      'Conversion to a sequence works',
      'Can be used as an object implementing a callback interface',
    ],
  },
  'ecmascript-binding/observable-array-no-leak-of-internals.window.js': {
    comment: 'Window-specific test',
    omittedTests: true,
  },
  'ecmascript-binding/observable-array-ownkeys.window.js': {
    comment: 'Window-specific test',
    omittedTests: true,
  },
  'ecmascript-binding/support/create-realm.js': {},
  'idlharness.any.js': {
    comment: 'TODO: Investigate this',
    expectedFailures: [
      'DOMException interface: existence and properties of interface object',
      'DOMException interface object length',
      'DOMException interface object name',
      'DOMException interface: existence and properties of interface prototype object',
      'DOMException interface: existence and properties of interface prototype object\'s "constructor" property',
      "DOMException interface: existence and properties of interface prototype object's @@unscopables property",
      'DOMException interface: attribute name',
      'DOMException interface: attribute message',
      'DOMException interface: attribute code',
      'DOMException interface: constant INDEX_SIZE_ERR on interface object',
      'DOMException interface: constant INDEX_SIZE_ERR on interface prototype object',
      'DOMException interface: constant DOMSTRING_SIZE_ERR on interface object',
      'DOMException interface: constant DOMSTRING_SIZE_ERR on interface prototype object',
      'DOMException interface: constant HIERARCHY_REQUEST_ERR on interface object',
      'DOMException interface: constant HIERARCHY_REQUEST_ERR on interface prototype object',
      'DOMException interface: constant WRONG_DOCUMENT_ERR on interface object',
      'DOMException interface: constant WRONG_DOCUMENT_ERR on interface prototype object',
      'DOMException interface: constant INVALID_CHARACTER_ERR on interface object',
      'DOMException interface: constant INVALID_CHARACTER_ERR on interface prototype object',
      'DOMException interface: constant NO_DATA_ALLOWED_ERR on interface object',
      'DOMException interface: constant NO_DATA_ALLOWED_ERR on interface prototype object',
      'DOMException interface: constant NO_MODIFICATION_ALLOWED_ERR on interface object',
      'DOMException interface: constant NO_MODIFICATION_ALLOWED_ERR on interface prototype object',
      'DOMException interface: constant NOT_FOUND_ERR on interface object',
      'DOMException interface: constant NOT_FOUND_ERR on interface prototype object',
      'DOMException interface: constant NOT_SUPPORTED_ERR on interface object',
      'DOMException interface: constant NOT_SUPPORTED_ERR on interface prototype object',
      'DOMException interface: constant INUSE_ATTRIBUTE_ERR on interface object',
      'DOMException interface: constant INUSE_ATTRIBUTE_ERR on interface prototype object',
      'DOMException interface: constant INVALID_STATE_ERR on interface object',
      'DOMException interface: constant INVALID_STATE_ERR on interface prototype object',
      'DOMException interface: constant SYNTAX_ERR on interface object',
      'DOMException interface: constant SYNTAX_ERR on interface prototype object',
      'DOMException interface: constant INVALID_MODIFICATION_ERR on interface object',
      'DOMException interface: constant INVALID_MODIFICATION_ERR on interface prototype object',
      'DOMException interface: constant NAMESPACE_ERR on interface object',
      'DOMException interface: constant NAMESPACE_ERR on interface prototype object',
      'DOMException interface: constant INVALID_ACCESS_ERR on interface object',
      'DOMException interface: constant INVALID_ACCESS_ERR on interface prototype object',
      'DOMException interface: constant VALIDATION_ERR on interface object',
      'DOMException interface: constant VALIDATION_ERR on interface prototype object',
      'DOMException interface: constant TYPE_MISMATCH_ERR on interface object',
      'DOMException interface: constant TYPE_MISMATCH_ERR on interface prototype object',
      'DOMException interface: constant SECURITY_ERR on interface object',
      'DOMException interface: constant SECURITY_ERR on interface prototype object',
      'DOMException interface: constant NETWORK_ERR on interface object',
      'DOMException interface: constant NETWORK_ERR on interface prototype object',
      'DOMException interface: constant ABORT_ERR on interface object',
      'DOMException interface: constant ABORT_ERR on interface prototype object',
      'DOMException interface: constant URL_MISMATCH_ERR on interface object',
      'DOMException interface: constant URL_MISMATCH_ERR on interface prototype object',
      'DOMException interface: constant QUOTA_EXCEEDED_ERR on interface object',
      'DOMException interface: constant QUOTA_EXCEEDED_ERR on interface prototype object',
      'DOMException interface: constant TIMEOUT_ERR on interface object',
      'DOMException interface: constant TIMEOUT_ERR on interface prototype object',
      'DOMException interface: constant INVALID_NODE_TYPE_ERR on interface object',
      'DOMException interface: constant INVALID_NODE_TYPE_ERR on interface prototype object',
      'DOMException interface: constant DATA_CLONE_ERR on interface object',
      'DOMException interface: constant DATA_CLONE_ERR on interface prototype object',
      'DOMException must be primary interface of new DOMException()',
      'Stringification of new DOMException()',
      'DOMException interface: new DOMException() must inherit property "name" with the proper type',
      'DOMException interface: new DOMException() must inherit property "message" with the proper type',
      'DOMException interface: new DOMException() must inherit property "code" with the proper type',
      'DOMException interface: new DOMException() must inherit property "INDEX_SIZE_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "DOMSTRING_SIZE_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "HIERARCHY_REQUEST_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "WRONG_DOCUMENT_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "INVALID_CHARACTER_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "NO_DATA_ALLOWED_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "NO_MODIFICATION_ALLOWED_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "NOT_FOUND_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "NOT_SUPPORTED_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "INUSE_ATTRIBUTE_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "INVALID_STATE_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "SYNTAX_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "INVALID_MODIFICATION_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "NAMESPACE_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "INVALID_ACCESS_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "VALIDATION_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "TYPE_MISMATCH_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "SECURITY_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "NETWORK_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "ABORT_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "URL_MISMATCH_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "QUOTA_EXCEEDED_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "TIMEOUT_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "INVALID_NODE_TYPE_ERR" with the proper type',
      'DOMException interface: new DOMException() must inherit property "DATA_CLONE_ERR" with the proper type',
      'DOMException must be primary interface of new DOMException("my message")',
      'Stringification of new DOMException("my message")',
      'DOMException interface: new DOMException("my message") must inherit property "name" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "message" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "code" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "INDEX_SIZE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "DOMSTRING_SIZE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "HIERARCHY_REQUEST_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "WRONG_DOCUMENT_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "INVALID_CHARACTER_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "NO_DATA_ALLOWED_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "NO_MODIFICATION_ALLOWED_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "NOT_FOUND_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "NOT_SUPPORTED_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "INUSE_ATTRIBUTE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "INVALID_STATE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "SYNTAX_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "INVALID_MODIFICATION_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "NAMESPACE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "INVALID_ACCESS_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "VALIDATION_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "TYPE_MISMATCH_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "SECURITY_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "NETWORK_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "ABORT_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "URL_MISMATCH_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "QUOTA_EXCEEDED_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "TIMEOUT_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "INVALID_NODE_TYPE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message") must inherit property "DATA_CLONE_ERR" with the proper type',
      'DOMException must be primary interface of new DOMException("my message", "myName")',
      'Stringification of new DOMException("my message", "myName")',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "name" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "message" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "code" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "INDEX_SIZE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "DOMSTRING_SIZE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "HIERARCHY_REQUEST_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "WRONG_DOCUMENT_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "INVALID_CHARACTER_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "NO_DATA_ALLOWED_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "NO_MODIFICATION_ALLOWED_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "NOT_FOUND_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "NOT_SUPPORTED_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "INUSE_ATTRIBUTE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "INVALID_STATE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "SYNTAX_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "INVALID_MODIFICATION_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "NAMESPACE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "INVALID_ACCESS_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "VALIDATION_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "TYPE_MISMATCH_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "SECURITY_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "NETWORK_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "ABORT_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "URL_MISMATCH_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "QUOTA_EXCEEDED_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "TIMEOUT_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "INVALID_NODE_TYPE_ERR" with the proper type',
      'DOMException interface: new DOMException("my message", "myName") must inherit property "DATA_CLONE_ERR" with the proper type',
      'QuotaExceededError interface: existence and properties of interface object',
      'QuotaExceededError interface object length',
      'QuotaExceededError interface object name',
      'QuotaExceededError interface: existence and properties of interface prototype object',
      'QuotaExceededError interface: existence and properties of interface prototype object\'s "constructor" property',
      "QuotaExceededError interface: existence and properties of interface prototype object's @@unscopables property",
      'QuotaExceededError interface: attribute quota',
      'QuotaExceededError interface: attribute requested',
    ],
  },
} satisfies TestRunnerConfig;
