load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_proc_macro", "rust_test")
load("//:build/wd_cc_library.bzl", "wd_cc_library")

rust_library(
    name = "cxx",
    srcs = glob(["src/**/*.rs"]),
    edition = "2024",
    link_deps = [
        ":core",
        "//src/rust/cxx/third-party:runtime",
        "@@//deps:rust_runtime",
    ],
    proc_macro_deps = [
        ":cxxbridge-macro",
    ],
    target_compatible_with = select({
        "@//build/config:no_build": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "@crates_vendor//:foldhash",
    ],
)

rust_test(
    name = "cxx_tests",
    crate = ":cxx",
    experimental_use_cc_common_link = select({
        "@platforms//os:windows": 0,
        "//conditions:default": 1,
    }),
    malloc = "//src/workerd/server:malloc",
    target_compatible_with = select({
        "@//build/config:no_build": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
)

alias(
    name = "codegen",
    actual = ":cxxbridge",
    visibility = ["//visibility:public"],
)

rust_library(
    name = "syntax",
    srcs = glob(["syntax/*.rs"]),
    crate_root = "syntax/mod.rs",
    edition = "2024",
    target_compatible_with = select({
        "@//build/config:no_build": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        "@crates_vendor//:proc-macro2",
        "@crates_vendor//:quote",
        "@crates_vendor//:syn",
    ],
)

rust_library(
    name = "gen",
    srcs = glob(["gen/src/*.rs"]),
    compile_data = ["include/cxx.h"],
    crate_root = "gen/src/mod.rs",
    edition = "2024",
    target_compatible_with = select({
        "@//build/config:no_build": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":syntax",
        "@crates_vendor//:codespan-reporting",
        "@crates_vendor//:proc-macro2",
        "@crates_vendor//:quote",
        "@crates_vendor//:syn",
    ],
)

rust_binary(
    name = "cxxbridge",
    srcs = glob(["gen/cmd/src/*.rs"]),
    compile_data = ["include/cxx.h"],
    edition = "2024",
    link_deps = ["@@//deps:rust_runtime"],
    target_compatible_with = select({
        "@//build/config:no_build": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":gen",
        ":syntax",
        "@crates_vendor//:clap",
        "@crates_vendor//:codespan-reporting",
        "@crates_vendor//:proc-macro2",
        "@crates_vendor//:quote",
        "@crates_vendor//:syn",
    ],
)

wd_cc_library(
    name = "core",
    srcs = ["src/cxx.cc"],
    hdrs = ["include/cxx.h"],
    include_prefix = "rust",
    linkstatic = True,
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "@capnp-cpp//src/kj:kj",
    ],
)

rust_proc_macro(
    name = "cxxbridge-macro",
    srcs = glob(["macro/src/*.rs"]),
    edition = "2024",
    proc_macro_deps = [
        "@crates_vendor//:rustversion",
    ],
    target_compatible_with = select({
        "@//build/config:no_build": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    visibility = ["//src/rust/cxx/tests:__pkg__"],
    deps = [
        ":gen",
        ":syntax",
        "@crates_vendor//:proc-macro2",
        "@crates_vendor//:quote",
        "@crates_vendor//:syn",
    ],
)

rust_library(
    name = "cxx-build",
    srcs = glob(["gen/build/src/*.rs"]),
    compile_data = [
        "include/cxx.h",
    ],
    edition = "2024",
    target_compatible_with = select({
        "@//build/config:no_build": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = [
        ":gen",
        ":syntax",
        "@crates_vendor//:cc",
        "@crates_vendor//:codespan-reporting",
        "@crates_vendor//:proc-macro2",
        "@crates_vendor//:quote",
        "@crates_vendor//:scratch",
        "@crates_vendor//:syn",
    ],
)

rust_library(
    name = "cxx-gen",
    srcs = glob(["gen/lib/src/*.rs"]),
    compile_data = ["include/cxx.h"],
    edition = "2024",
    target_compatible_with = select({
        "@//build/config:no_build": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
    deps = [
        ":gen",
        ":syntax",
        "@crates_vendor//:cc",
        "@crates_vendor//:proc-macro2",
        "@crates_vendor//:quote",
        "@crates_vendor//:syn",
    ],
)

platform(
    name = "x64_windows-clang-cl",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:windows",
        "@bazel_tools//tools/cpp:clang-cl",
    ],
)
