// Copyright (c) 2017-2022 Cloudflare, Inc.
// Licensed under the Apache 2.0 license found in the LICENSE file or at:
//     https://opensource.org/licenses/Apache-2.0

#include "jsg-test.h"

namespace workerd::jsg::test {
namespace {

// Compile Wasm eagerly so its code-addition events arrive before the module constructor returns.
V8System v8System(
    {"--allow-natives-syntax", "--no-wasm-lazy-compilation"}, JitCodeEventTracking::YES);

struct EvalContext: public Object, public ContextGlobal {
  JSG_RESOURCE_TYPE(EvalContext) {}
};
JSG_DECLARE_ISOLATE_TYPE(EvalIsolate, EvalContext);

class HistogramSink final: public V8HistogramSink {
 public:
  void addSample(int sample) override {
    samples.fetch_add(1, std::memory_order_relaxed);
  }

  std::atomic<uint> samples = 0;
};

class HistogramObserver final: public IsolateObserver {
 public:
  kj::Maybe<V8HistogramSink&> tryCreateV8HistogramSink(
      kj::StringPtr name, int min, int max, size_t buckets) override {
    if (name == "V8.SnapshotDeserializeIsolateMicroSeconds"_kj) return snapshot;
    if (name == "V8.CompileScriptMicroSeconds"_kj) return compile;
    return kj::none;
  }

  HistogramSink snapshot;
  HistogramSink compile;
};

void compileScript(EvalIsolate& isolate, kj::StringPtr source) {
  isolate.runInLockScope([&](EvalIsolate::Lock& lock) {
    JSG_WITHIN_CONTEXT_SCOPE(
        lock, lock.newContext<EvalContext>().getHandle(lock.v8Isolate), [&](jsg::Lock& js) {
      auto script = v8::Script::Compile(js.v8Context(), v8Str(js.v8Isolate, source));
      KJ_ASSERT(!script.IsEmpty());
    });
  });
}

KJ_TEST("V8 histogram callbacks capture snapshot and script compilation samples") {
  auto observer = kj::heap<HistogramObserver>();
  auto& observed = *observer;
  EvalIsolate isolate(v8System, newIsolateGroup(), nullptr, kj::mv(observer));
  KJ_EXPECT(observed.snapshot.samples.load() > 0);

  auto before = observed.compile.samples.load();
  compileScript(isolate, "function square(x) { return x * x; } square(4);"_kj);
  KJ_EXPECT(observed.compile.samples.load() > before);
}

KJ_TEST("V8 histogram sinks are routed to their own isolate") {
  auto firstObserver = kj::heap<HistogramObserver>();
  auto& first = *firstObserver;
  EvalIsolate firstIsolate(v8System, newIsolateGroup(), nullptr, kj::mv(firstObserver));
  auto firstSnapshotSamples = first.snapshot.samples.load();
  auto firstCompileSamples = first.compile.samples.load();

  {
    auto secondObserver = kj::heap<HistogramObserver>();
    auto& second = *secondObserver;
    EvalIsolate secondIsolate(v8System, newIsolateGroup(), nullptr, kj::mv(secondObserver));
    KJ_EXPECT(second.snapshot.samples.load() > 0);
    auto secondCompileSamples = second.compile.samples.load();
    compileScript(secondIsolate, "function cube(x) { return x * x * x; } cube(3);"_kj);
    KJ_EXPECT(second.compile.samples.load() > secondCompileSamples);
    KJ_EXPECT(first.snapshot.samples.load() == firstSnapshotSamples);
    KJ_EXPECT(first.compile.samples.load() == firstCompileSamples);
  }

  compileScript(firstIsolate, "function twice(x) { return x + x; } twice(5);"_kj);
  KJ_EXPECT(first.compile.samples.load() > firstCompileSamples);
}

KJ_TEST("V8 histogram creation tolerates a missing current isolate or IsolateBase") {
  KJ_EXPECT(
      IsolateBase::createV8Histogram("V8.CompileScriptMicroSeconds", 0, 1000000, 50) == nullptr);

  EvalIsolate isolate(v8System, newIsolateGroup(), nullptr, kj::heap<HistogramObserver>());
  isolate.runInLockScope([&](EvalIsolate::Lock& lock) {
    auto* base = lock.v8Isolate->GetData(SET_DATA_ISOLATE_BASE);
    lock.v8Isolate->SetData(SET_DATA_ISOLATE_BASE, nullptr);
    KJ_DEFER(lock.v8Isolate->SetData(SET_DATA_ISOLATE_BASE, base));
    KJ_EXPECT(
        IsolateBase::createV8Histogram("V8.CompileScriptMicroSeconds", 0, 1000000, 50) == nullptr);
  });
}

KJ_TEST("Code statistics accumulate generated bytecode") {
  EvalIsolate isolate(v8System, newIsolateGroup(), nullptr, kj::heap<IsolateObserver>());
  auto before = isolate.getCodeStatistics();
  compileScript(isolate, "let numbers = [1, 2, 3]; numbers.map(x => x * x);"_kj);
  auto first = isolate.getCodeStatistics();
  KJ_EXPECT(first.bytecodeCount > before.bytecodeCount);
  KJ_EXPECT(first.bytecodeBytes > before.bytecodeBytes);

  compileScript(isolate, "let names = ['a', 'b']; names.join(',');"_kj);
  auto second = isolate.getCodeStatistics();
  KJ_EXPECT(second.bytecodeCount > first.bytecodeCount);
  KJ_EXPECT(second.bytecodeBytes > first.bytecodeBytes);
}

KJ_TEST("Code statistics accumulate JavaScript machine code") {
  Evaluator<EvalContext, EvalIsolate> e(v8System);
  auto before = e.getIsolate().getCodeStatistics();
  e.expectEval(R"(
    function square(x) { return x * x; }
    %PrepareFunctionForOptimization(square);
    square(4);
    %OptimizeFunctionOnNextCall(square);
    square(5);
  )",
      "number", "25");
  auto after = e.getIsolate().getCodeStatistics();
  KJ_EXPECT(after.jitCodeCount > before.jitCodeCount);
  KJ_EXPECT(after.jitCodeBytes > before.jitCodeBytes);
  KJ_EXPECT(after.wasmCodeCount == before.wasmCodeCount);
  KJ_EXPECT(after.wasmCodeBytes == before.wasmCodeBytes);
}

KJ_TEST("Code statistics accumulate Wasm machine code") {
  Evaluator<EvalContext, EvalIsolate> e(v8System);
  e.setAllowEval(true);
  KJ_DEFER(e.setAllowEval(false));
  auto before = e.getIsolate().getCodeStatistics();
  e.expectEval(R"(
    // A module exporting answer(), which returns the i32 constant 42.
    const module = new WebAssembly.Module(new Uint8Array([
      0, 97, 115, 109, 1, 0, 0, 0,
      1, 5, 1, 96, 0, 1, 127,
      3, 2, 1, 0,
      7, 10, 1, 6, 97, 110, 115, 119, 101, 114, 0, 0,
      10, 6, 1, 4, 0, 65, 42, 11,
    ]));
    new WebAssembly.Instance(module).exports.answer();
  )",
      "number", "42");
  auto after = e.getIsolate().getCodeStatistics();
  KJ_EXPECT(after.wasmCodeCount > before.wasmCodeCount);
  KJ_EXPECT(after.wasmCodeBytes > before.wasmCodeBytes);
}

KJ_TEST("eval() is blocked") {
  Evaluator<EvalContext, EvalIsolate> e(v8System);
  e.expectEval("eval('123')", "throws",
      "EvalError: Code generation from strings disallowed for this context");
  e.expectEval("new Function('a', 'b', 'return a + b;')(123, 321)", "throws",
      "EvalError: Code generation from strings disallowed for this context");

  // eval() with no args or a non-string arg is allowed even when eval is blocked
  // (V8 returns the value as-is per spec since there is no string to compile).
  e.expectEval("eval()", "undefined", "undefined");
  e.expectEval("eval(undefined)", "undefined", "undefined");

  // new Function() with no arguments is allowed even when eval is blocked (the
  // synthesized source matches the known empty-body, no-parameter pattern).
  e.expectEval("typeof new Function()", "string", "function");

  // new Function() with params and an undefined body is blocked (the body becomes
  // the string "undefined" via ToString, producing a non-empty source).
  e.expectEval("new Function('a', 'b', undefined)", "throws",
      "EvalError: Code generation from strings disallowed for this context");

  // Extending Function with super() and no arguments is also allowed.
  e.expectEval("class Foo extends Function { constructor() { super(); } }; typeof new Foo()",
      "string", "function");

  e.getIsolate().runInLockScope([&](EvalIsolate::Lock& lock) { lock.setAllowEval(true); });

  e.expectEval("eval('123')", "number", "123");
  e.expectEval("new Function('a', 'b', 'return a + b;')(123, 321)", "number", "444");

  e.getIsolate().runInLockScope([&](EvalIsolate::Lock& lock) { lock.setAllowEval(false); });

  e.expectEval("eval('123')", "throws",
      "EvalError: Code generation from strings disallowed for this context");
  e.expectEval("new Function('a', 'b', 'return a + b;')(123, 321)", "throws",
      "EvalError: Code generation from strings disallowed for this context");

  // Note: It would be nice to test as well that WebAssembly is blocked, but that requires
  //   setting up an event loop since the WebAssembly calls are all async. We'll test this
  //   elsewhere.
}

// ========================================================================================

struct ConfigContext: public Object, public ContextGlobal {
  struct Nested: public Object {
    JSG_RESOURCE_TYPE(Nested, int configuration) {
      KJ_EXPECT(configuration == 123, configuration);
    }
  };
  struct OtherNested: public Object {
    JSG_RESOURCE_TYPE(OtherNested) {}
  };

  JSG_RESOURCE_TYPE(ConfigContext) {
    JSG_NESTED_TYPE(Nested);
    JSG_NESTED_TYPE(OtherNested);
  }
};
JSG_DECLARE_ISOLATE_TYPE(
    ConfigIsolate, ConfigContext, ConfigContext::Nested, ConfigContext::OtherNested);

KJ_TEST("configuration values reach nested type declarations") {
  {
    ConfigIsolate isolate(v8System, newIsolateGroup(), 123, kj::heap<IsolateObserver>());
    isolate.runInLockScope([&](ConfigIsolate::Lock& lock) {
      jsg::Lock& js = lock;
      js.withinHandleScope([&] { lock.newContext<ConfigContext>().getHandle(lock); });
    });
  }
  {
    KJ_EXPECT_LOG(ERROR, "failed: expected configuration == 123");
    ConfigIsolate isolate(v8System, newIsolateGroup(), 456, kj::heap<IsolateObserver>());
    isolate.runInLockScope([&](ConfigIsolate::Lock& lock) {
      jsg::Lock& js = lock;
      js.withinHandleScope([&] { lock.newContext<ConfigContext>().getHandle(lock); });
    });
  }
}

}  // namespace
}  // namespace workerd::jsg::test
