// Generated from the corpus of failure-case url tests in WPT
KJ_ASSERT(Url::tryParse("http://f:b/c"_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://f: /c"_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://f:fifty-two/c"_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://f:999999/c"_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("non-special://f:999999/c"_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://f: 21 / b ? d # e "_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[1::2]:3:4"_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://2001::1"_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://2001::1]"_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://2001::1]:80"_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[::127.0.0.1.]"_kj, kj::Maybe("http://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("file://example:1/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("file://example:test/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("file://example%/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("file://[example]/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://user:pass@/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo:-80/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http:/:@/www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://user@/www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http:@/www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http:/@/www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://@/www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https:@/www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http:a:b@/www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http:/a:b@/www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a:b@/www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http::@/www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http:@:www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http:/@:www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://@:www.example.com"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://example example.com"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://Goo%20 goo%7C|.com"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[:]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://GOO 　goo.com"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://﷐zyx.com"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://%ef%b7%90zyx.com"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("https://�"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://%EF%BF%BD"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a.b.c.xn--pokxncvks"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://10.0.0.xn--pokxncvks"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a.b.c.XN--pokxncvks"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a.b.c.Xn--pokxncvks"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://10.0.0.XN--pokxncvks"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://10.0.0.xN--pokxncvks"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://％４１.com"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://%ef%bc%85%ef%bc%94%ef%bc%91.com"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://％００.com"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://%ef%bc%85%ef%bc%90%ef%bc%90.com"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://%zz%66%a.com"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://%25"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://hello%00"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://192.168.0.257"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://%3g%78%63%30%2e%30%32%35%30%2E.01"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://192.168.0.1 hello"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("https://x x:12"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://[www.google.com]/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://[google.com]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[::1.2.3.4x]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[::1.2.3.]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[::1.2.]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[::.1.2]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[::1.]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[::.1]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://[::%31]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://%5B::1]"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("i"_kj, kj::Maybe("sc:sd"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("i"_kj, kj::Maybe("sc:sd/sd"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("../i"_kj, kj::Maybe("sc:sd"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("../i"_kj, kj::Maybe("sc:sd/sd"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("/i"_kj, kj::Maybe("sc:sd"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("/i"_kj, kj::Maybe("sc:sd/sd"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("?i"_kj, kj::Maybe("sc:sd"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("?i"_kj, kj::Maybe("sc:sd/sd"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("sc://@/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://te@s:t@/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://:/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://:12/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://a\0b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://a b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://a<b"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://a>b"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://a[b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://a\\b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://a]b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://a^b"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("sc://a|b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a\0b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a%b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a<b"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a>b"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a[b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a]b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a^b"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://a|b/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ab/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%00st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%01st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%02st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%03st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%04st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%05st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%06st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%07st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%08st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%09st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%0Ast/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%0Bst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%0Cst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%0Dst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%0Est/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%0Fst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%10st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%11st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%12st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%13st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%14st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%15st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%16st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%17st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%18st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%19st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%1Ast/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%1Bst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%1Cst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%1Dst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%1Est/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%1Fst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%20st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%23st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%25st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%2Fst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%3Ast/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%3Cst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%3Est/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%3Fst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%40st/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%5Bst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%5Cst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%5Dst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%7Cst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://ho%7Fst/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("ftp://example.com%80/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("ftp://example.com%A0/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://example.com%80/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://example.com%A0/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http:"_kj, kj::Maybe("https://example.org/foo/bar"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://10000000000"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://4294967296"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://0xffffffff1"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://256.256.256.256"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("https://0x100000000/test"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://256.0.0.1/test"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("file://%43%3A"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("file://%43%7C"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("file://%43|"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("file://C%7C"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("file://%43%7C/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://%43%7C/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("asdf://%43|/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("\\\\\\.\\Y:"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("\\\\\\.\\y:"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://[0:1:2:3:4:5:6:7:8]"_kj, kj::Maybe("http://example.net/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("https://[0::0::0]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://[0:.0]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://[0:0:]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://[0:1:2:3:4:5:6:7.0.0.0.1]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://[0:1.00.0.0.0]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://[0:1.290.0.0.0]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://[0:1.23.23]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://?"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://#"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://f:4294967377/c"_kj, kj::Maybe("http://example.org/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://f:18446744073709551697/c"_kj, kj::Maybe("http://example.org/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://f:340282366920938463463374607431768211537/c"_kj, kj::Maybe("http://example.org/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("non-special://[:80/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://[::127.0.0.0.1]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("a"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("a/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("a//"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("test-a-colon.html"_kj, kj::Maybe("a:"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("test-a-colon-b.html"_kj, kj::Maybe("a:b"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("file://­/p"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("file://%C2%AD/p"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("file://xn--/p"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("#"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("?"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://1.2.3.4.5"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://1.2.3.4.5."_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://0..0x300/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://0..0x300./"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://256.256.256.256.256"_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://256.256.256.256.256."_kj, kj::Maybe("http://other.com/"_kj)) == kj::none);
KJ_ASSERT(Url::tryParse("http://1.2.3.08"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://1.2.3.08."_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://1.2.3.09"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://09.2.3.4"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://09.2.3.4."_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://01.2.3.4.5"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://01.2.3.4.5."_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://0x100.2.3.4"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://0x100.2.3.4."_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://0x1.2.3.4.5"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://0x1.2.3.4.5."_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo.1.2.3.4"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo.1.2.3.4."_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo.2.3.4"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo.2.3.4."_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo.09"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo.09."_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo.0x4"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo.0x4."_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://0999999999999999999/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo.0x"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://foo.0XFfFfFfFfFfFfFfFfFfAcE123"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("http://💩.123/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://\0y"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://￿y"_kj) == kj::none);
KJ_ASSERT(Url::tryParse(""_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://­/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://%C2%AD/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("https://xn--/"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("data://:443"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("data://test:test"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("data://[:1]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("javascript://:443"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("javascript://test:test"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("javascript://[:1]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("mailto://:443"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("mailto://test:test"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("mailto://[:1]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("intent://:443"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("intent://test:test"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("intent://[:1]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("urn://:443"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("urn://test:test"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("urn://[:1]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("turn://:443"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("turn://test:test"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("turn://[:1]"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("stun://:443"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("stun://test:test"_kj) == kj::none);
KJ_ASSERT(Url::tryParse("stun://[:1]"_kj) == kj::none);
