name: 'WPT Report'
on:
  workflow_call:
    inputs:
      image:
        description: 'Runner image to use'
        required: true
        type: string
      logs_artifact:
        description: 'Name of artifact containing test logs'
        required: true
        type: string
      report_artifact:
        description: 'Name of artifact to use for WPT report JSON file'
        required: true
        type: string

permissions:
  # Read repo
  contents: read
  # Read/write artifacts
  actions: write
jobs:
  wpt-report:
    runs-on: ${{ inputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Download test logs
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: ${{ inputs.logs_artifact }}
          path: testlogs
      - name: Generate WPT report and stats
        run: ./tools/cross/wpt_logs.py --print-stats --write-report=wpt-report.json testlogs/ >> $GITHUB_STEP_SUMMARY
      - name: Upload WPT report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.report_artifact }}
          path: wpt-report.json
