name: Dependency updater

on:
  schedule:
    # Run at 00:00 UTC every Sunday
    - cron: '0 0 * * 0'
  # Allow manual triggering for testing
  workflow_dispatch:

concurrency:
  group: deps-updater
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          token: ${{ secrets.DEVPROD_PAT }}
          ref: main
      - name: Update dependencies
        run: build/deps/update-deps.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update rust dependencies
        run: bazel run //deps/rust:crates_vendor -- --repin full
      - name: Open pull request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "update dependencies to latest version"
          branch: "automatic-update-deps"
          title: "Update dependencies"
          token: ${{ secrets.DEVPROD_PAT }}
          author: "Workers DevProd <workers-devprod@cloudflare.com>"
          committer: "Workers DevProd <workers-devprod@cloudflare.com>"
          body: |
            This is an automated pull request for updating the dependencies of workerd.
          delete-branch: true
      - name: Enable Pull Request Automerge
        run: gh pr merge --rebase --auto ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.DEVPROD_PAT }}
