name: "Just say no to fixup commits"
on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  block-fixup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Block Fixup Commit Merge
      uses: 13rac1/block-fixup-merge-action@v2.0.0

