name: "Just say no to fixup commits"
on:
  workflow_call:

jobs:
  block-fixup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Block Fixup Commit Merge
      uses: 13rac1/block-fixup-merge-action@bd5504fb9ca0253e109d98eb86b7debc01970cdc # v2.0.0

