name: Run internal build

on:
  pull_request:

concurrency:
  # Cancel existing builds for the same PR.
  # Otherwise, all other builds will be allowed to run through.
  group: internal-build.yml-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  internal-build:
    if: "${{! github.event.pull_request.head.repo.fork}}" # Don't run on forks
    runs-on: ubuntu-latest
    steps:
      # Try to checkout the merge commit - will fail if PR isn't mergeable
      - uses: actions/checkout@v4
        id: checkout_merge
        continue-on-error: true
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          show-progress: false

      # Fail the workflow if checkout failed (PR isn't mergeable)
      - name: Fail if PR isn't mergeable
        if: steps.checkout_merge.outcome != 'success'
        run: |
          echo "The pull request is not mergeable. Please rebase and resolve any conflicts."
          exit 1

      - name: Get merge commit SHA
        id: get_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Run internal build
        env:
          CI_URL: ${{ secrets.CI_URL }}
          CI_CLIENT_ID: ${{ secrets.CI_CF_ACCESS_CLIENT_ID }}
          CI_CLIENT_SECRET: ${{ secrets.CI_CF_ACCESS_CLIENT_SECRET }}
        run: |
          python3 -u ./tools/cross/internal_build.py \
            ${{github.event.pull_request.number}} \
            ${{steps.get_sha.outputs.sha}} \
            ${{github.event.pull_request.head.sha}} \
            ${{github.run_attempt}} \
            "${{github.event.pull_request.head.ref}}" \
            $CI_URL \
            $CI_CLIENT_ID \
            $CI_CLIENT_SECRET
